- accounts/kethereum/build.gradle
- accounts/kethereum/src/main/java/pm/gnosis/heimdall/accounts/data/db/AccountsDatabase.kt
- accounts/kethereum/src/main/java/pm/gnosis/heimdall/accounts/repositories/impl/KethereumAccountsRepository.kt
- accounts/kethereum/src/main/java/pm/gnosis/heimdall/accounts/repositories/impl/models/db/AccountDb.kt
- app/src/main/java/pm/gnosis/heimdall/common/di/module/ApplicationModule.kt
- app/src/main/java/pm/gnosis/heimdall/ui/base/BaseActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/security/SecurityViewModel.kt
- security/build.gradle
- security/src/main/java/pm/gnosis/heimdall/security/db/Encrypted.kt
- security/src/main/java/pm/gnosis/heimdall/security/exceptions/exceptions.kt
- security/src/main/java/pm/gnosis/heimdall/security/impls/AesEncryptionManager.kt
- utils/src/main/java/pm/gnosis/utils/NumberUtils.kt
Closes #55.
- Store mnemonic phrase encrypted
- Store private keys encrypted
> Closes #55: Use encryption for private data

- app/src/main/java/pm/gnosis/heimdall/common/di/components/ViewComponent.kt
- app/src/main/java/pm/gnosis/heimdall/common/di/modules/ViewModelFactoryModule.kt
- app/src/main/java/pm/gnosis/heimdall/common/di/modules/ViewModule.kt
- app/src/main/java/pm/gnosis/heimdall/ui/account/AccountContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/account/AccountFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/multisig/details/MultisigDetailsActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/multisig/details/MultisigDetailsContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/multisig/details/MultisigDetailsViewModel.kt
- app/src/main/res/layout/layout_multisig_details.xml
- app/src/main/res/menu/multisig_details_menu.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/ui/account/AccountViewModelTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/multisig/details/MultisigDetailsViewModelTest.kt
- heimdall-common/src/main/java/pm/gnosis/heimdall/common/utils/ContextUtils.kt
- heimdall-common/src/main/java/pm/gnosis/heimdall/common/utils/QrCodeUtils.kt
- utils/src/main/java/pm/gnosis/utils/exceptions/InvalidAddressException.kt
Closes #62 .
- Add multisig share options
> WA-29: Add multisig share options. Closes #62

- app/src/main/java/pm/gnosis/heimdall/ui/multisig/details/MultisigDetailsActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/multisig/details/MultisigDetailsContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/multisig/details/MultisigDetailsViewModel.kt
- app/src/main/res/layout/dialog_multisig_add_input.xml
- app/src/main/res/layout/dialog_token_add_input.xml
- app/src/main/res/layout/layout_multisig_details.xml
- app/src/main/res/menu/multisig_details_menu.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/ui/multisig/details/MultisigDetailsViewModelTest.kt
- heimdall-common/src/main/java/pm/gnosis/heimdall/common/utils/ContextUtils.kt
- Add option to edit name and delete multisig
> WA-44: Add option to edit name and delete multisig

- accounts/kethereum/src/main/java/pm/gnosis/heimdall/accounts/data/db/AccountsDatabase.kt
- app/src/main/java/pm/gnosis/heimdall/common/di/components/ApplicationComponent.kt
- app/src/main/java/pm/gnosis/heimdall/common/di/components/ViewComponent.kt
- app/src/main/java/pm/gnosis/heimdall/data/db/GnosisAuthenticatorDb.kt
- app/src/main/java/pm/gnosis/heimdall/ui/account/AccountActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/addressbook/add/AddressBookAddEntryActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/addressbook/detail/AddressBookEntryDetailsActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/addressbook/list/AddressBookActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/authenticate/AuthenticateActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/base/BaseActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/GenerateMnemonicActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/RestoreAccountActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/AddExistingSafeFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/DeployNewSafeFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/SafeDetailsActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/info/SafeInfoFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsAdapter.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsViewModel.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/overview/SafesOverviewActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/security/SecurityActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/settings/network/NetworkSettingsActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/settings/tokens/TokenManagementActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/splash/SplashActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/add/AddTokenActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/balances/TokenBalancesFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/info/TokenInfoActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactiondetails/TransactionDetailsActivity.kt
- buildsystem/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
> Update Gradle and Kotlin

- app/src/main/java/pm/gnosis/heimdall/common/di/components/ApplicationComponent.kt
- app/src/main/java/pm/gnosis/heimdall/common/di/components/ViewComponent.kt
- app/src/main/java/pm/gnosis/heimdall/ui/dialogs/base/BaseDialog.kt
- app/src/main/java/pm/gnosis/heimdall/ui/dialogs/share/BaseShareAddressDialog.kt
- app/src/main/java/pm/gnosis/heimdall/ui/dialogs/share/ShareSafeAddressDialog.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/SafeDetailsActivity.kt
- app/src/main/res/drawable/ic_qr_toolbar_24dp.xml
- app/src/main/res/layout/dialog_address_share.xml
- app/src/main/res/menu/safe_details_menu.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
> WA-61: Add share dialog

- build.gradle
- buildsystem/dependencies.gradle
> Update gradle and build tools

- app/src/main/java/pm/gnosis/heimdall/data/remote/impls/SimpleEthereumJsonRpcRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultGnosisSafeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTokenRepository.kt
- Use 40 char long address for network calls
> Use valid address string for network calls

- app/src/main/AndroidManifest.xml
Closes WA-69.
- Force portrait mode for whole app
> WA-69: Forced portrait mode for the whole app

- app/src/main/java/pm/gnosis/heimdall/ui/account/AccountActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/OnboardingIntro.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/SetupSafeIntroActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/password/PasswordSetupActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/DeployNewSafeFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/splash/SplashActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/BaseTransactionActivity.kt
- app/src/main/java/pm/gnosis/heimdall/utils/CurrencyUtils.kt
- app/src/main/res/layout/layout_safe_overview.xml
- app/src/main/res/layout/layout_transaction_details_asset_transfer.xml
- app/src/main/res/layout/layout_transaction_details_generic.xml
- app/src/main/res/values/strings.xml
- models/src/main/java/pm/gnosis/models/Wei.kt
Closes WA-52.
- Format wei values as ether if too large
- Move "Get Started" screen to beginning of onboarding
> WA-52: Currency formatting; Minor Fixes

- README.md
> WA-47: Update README

- accounts/kethereum/src/test/java/pm/gnosis/heimdall/accounts/repositories/impls/KethereumAccountsRepositoryTest.kt
- security/src/main/java/pm/gnosis/heimdall/security/EncryptionManager.kt
- security/src/main/java/pm/gnosis/heimdall/security/db/Encrypted.kt
- security/src/main/java/pm/gnosis/heimdall/security/impls/AesEncryptionManager.kt
Closes WA-95.
-  Use different iv for each encrypted value
> WA-95: Use different iv for each encrypted value

- security/src/main/java/pm/gnosis/heimdall/security/EncryptionManager.kt
- security/src/main/java/pm/gnosis/heimdall/security/impls/AesEncryptionManager.kt
- security/src/test/java/pm/gnosis/heimdall/security/impls/AesEncryptionManagerTest.kt
- Remove dependencies to SecretKey in encryption manager 
> Refactored EncryptionManager

- app/src/main/java/pm/gnosis/heimdall/common/di/components/ApplicationComponent.kt
- app/src/main/java/pm/gnosis/heimdall/common/di/modules/ApplicationBindingsModule.kt
- app/src/main/java/pm/gnosis/heimdall/common/di/modules/ApplicationModule.kt
- app/src/main/java/pm/gnosis/heimdall/data/remote/EthGasStationApi.kt
- app/src/main/java/pm/gnosis/heimdall/data/remote/models/EthGasStationPrices.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/TransactionRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/GnosisSafeTransactionRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/models/GasEstimate.kt
- app/src/main/java/pm/gnosis/heimdall/helpers/GasPriceHelper.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/SafeDetailsActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/BaseTransactionActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/CreateTransactionActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/ViewTransactionActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/ViewTransactionContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/ViewTransactionViewModel.kt
- app/src/main/java/pm/gnosis/heimdall/utils/CurrencyUtils.kt
- app/src/main/res/drawable/rounded_border_background.xml
- app/src/main/res/layout/include_gas_price_selection.xml
- app/src/main/res/layout/layout_view_transaction.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/helpers/EtherGasStationGasPriceHelperTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/transactions/ViewTransactionViewModelTest.kt
- utils-testing/src/main/java/pm.gnosis.tests.utils/MockUtils.kt
Closes WA-86.
- Added option to select transaction speed
> WA-86: Added option to select transaction speed

- app-core/src/main/java/pm/gnosis/heimdall/data/remote/models/TransactionReceipt.kt
- app/schemas/pm.gnosis.heimdall.data.db.GnosisAuthenticatorDb/1.json
- app/src/main/java/pm/gnosis/heimdall/data/db/GnosisAuthenticatorDb.kt
- app/src/main/java/pm/gnosis/heimdall/data/db/daos/DescriptionsDao.kt
- app/src/main/java/pm/gnosis/heimdall/data/db/models/TransactionPublishStatusDb.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/TransactionRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultGnosisSafeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/GnosisSafeTransactionRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/IpfsTransactionDetailsRepository.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsAdapter.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsViewModel.kt
- app/src/main/res/layout/layout_safe_transactions_item.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsViewModelTest.kt
Closes WA-89.
- Show transaction status in safe transaction list
> WA-89: Show transaction status in list

- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/SetupSafeIntroActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/account/create/GenerateMnemonicActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/account/restore/RestoreAccountActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/password/PasswordSetupActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsAdapter.kt
- app/src/main/java/pm/gnosis/heimdall/ui/security/unlock/UnlockActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/security/unlock/UnlockContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/security/unlock/UnlockViewModel.kt
- app/src/main/java/pm/gnosis/heimdall/ui/splash/SplashActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/ViewTransactionActivity.kt
- app/src/main/java/pm/gnosis/heimdall/utils/DateTimeUtils.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/ui/security/unlock/UnlockViewModelTest.kt
- heimdall-common/src/main/java/pm/gnosis/heimdall/common/utils/ContextUtils.kt
Closes WA-88.
- Ask for credentials before submitting transaction
> WA-88: Ask for credentials before submitting transaction

- app/src/main/java/pm/gnosis/heimdall/common/di/components/ViewComponent.kt
- app/src/main/java/pm/gnosis/heimdall/common/di/modules/ApplicationBindingsModule.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/GnosisSafeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultGnosisSafeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/helpers/AddressStore.kt
- app/src/main/java/pm/gnosis/heimdall/helpers/SignatureStore.kt
- app/src/main/java/pm/gnosis/heimdall/helpers/ValueStore.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/AddSafeContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/AddSafeViewModel.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/DeployNewSafeFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/ExecuteTransactionActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/ViewTransactionViewModel.kt
- app/src/main/res/layout/layout_additional_owner_item.xml
- app/src/main/res/layout/layout_deploy_new_safe.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/helpers/SimpleSignatureStoreTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/safe/add/AddSafeViewModelTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/transactions/ViewTransactionViewModelTest.kt
- heimdall-common/src/main/java/pm/gnosis/heimdall/common/utils/AndroidUtils.kt
- heimdall-common/src/main/java/pm/gnosis/heimdall/common/utils/ObservableUtils.kt
- ticker/src/main/java/pm/gnosis/ticker/data/repositories/impls/DefaultTickerRepository.kt
- ticker/src/main/java/pm/gnosis/ticker/data/repositories/models/Currency.kt
Closes WA-90.
- Add multiple users when creating a safe
> WA-90: Adjust deploy new safe screen

- app-core/build.gradle
- app/build.gradle
- app/src/main/java/pm/gnosis/heimdall/data/db/daos/ERC20TokenDao.kt
- app/src/main/java/pm/gnosis/heimdall/data/remote/EthereumJsonRpcRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/remote/impls/SimpleEthereumJsonRpcRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultGnosisSafeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/GnosisSafeTransactionRepository.kt
- app/src/main/res/raw/verified_tokens.json
- app/src/mainnet/res/raw/verified_tokens.json
- build.gradle
Closes WA-82.
- Added kovan contract addresses
- Changed to kovan infura endpoint
- Fixed bug with missing "from" when estimating
> WA-82: Enable Kovan

- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/AddExistingSafeFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/info/SafeSettingsFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/ExecuteTransactionActivity.kt
> WA-96: Check usage of subscribeOn(AndroidSchedulers.mainThread())

- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/AddExistingSafeFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/AddSafeContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/AddSafeViewModel.kt
- app/src/main/res/layout/layout_add_existing_safe.xml
- app/src/test/java/pm/gnosis/heimdall/ui/safe/add/AddSafeViewModelTest.kt
> WA-91: Adjust add existing safe flow

- app/src/main/AndroidManifest.xml
> WA-106: Disable Google's Auto Backup

- app-core/build.gradle
- app-core/src/main/java/pm/gnosis/heimdall/utils/GnoSafeUrlParser.kt
- app-core/src/test/java/pm/gnosis/heimdall/utils/GnoSafeUrlParserTest.kt
- models/src/main/java/pm/gnosis/models/Wei.kt
Closes WA-107.
- Added tests for GnoSafeUrlParser
- Fixed bug in GnoSafeUrlParser with null values
> WA-107: Added tests for GnoSafeUrlParser

- app/src/main/java/pm/gnosis/heimdall/ui/settings/tokens/TokenManagementAdapter.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/balances/TokenBalancesAdapter.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/info/TokenInfoActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/ReceiptTransactionActivity.kt
- app/src/main/java/pm/gnosis/heimdall/utils/AppUtils.kt
- app/src/main/res/layout/layout_token_info.xml
- app/src/main/res/layout/layout_tokens_item.xml
- app/src/main/res/layout/layout_tokens_item_balance.xml
- app/src/main/res/values/static_strings.xml
- app/src/main/res/values/strings.xml
- Adjust verified tokens screen
> WA-124: Adjust verified tokens screen

- app/build.gradle
- app/src/main/java/pm/gnosis/heimdall/ui/account/AccountActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/account/AccountContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/account/AccountViewModel.kt
- app/src/main/java/pm/gnosis/heimdall/utils/CurrencyUtils.kt
- app/src/main/res/layout/layout_account.xml
- app/src/main/res/menu/account_menu.xml
- app/src/main/res/values/static_strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/ui/account/AccountViewModelTest.kt
- heimdall-common/src/main/java/pm/gnosis/heimdall/common/utils/ObservableUtils.kt
- Adjust the design of the Account Screen
> WA-134: Adjust the design of the Account Screen

- app/src/main/java/pm/gnosis/heimdall/ui/addressbook/add/AddressBookAddEntryActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/AddSafeViewModel.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/DeployNewSafeFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/add/AddTokenActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/balances/TokenBalancesFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/details/base/BaseEditableTransactionDetailsFragment.kt
- app/src/main/java/pm/gnosis/heimdall/utils/AppUtils.kt
- app/src/main/res/layout/dialog_address_input.xml
- Some fields with address input only supported raw addresses. This adds support for ERC67 in those fields.
> WA-136: Add support for scanning ERC67 schemes.

- app/src/main/java/pm/gnosis/heimdall/ui/account/AccountActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/addressbook/add/AddressBookAddEntryActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/addressbook/list/AddressBookActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/authenticate/AuthenticateActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/base/BaseActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/account/create/GenerateMnemonicActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/account/restore/RestoreAccountActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/add/AddSafeActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/SafeDetailsActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/info/SafeSettingsActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/selection/SelectSafeActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/settings/SettingsActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/settings/network/NetworkSettingsActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/settings/security/SecuritySettingsActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/settings/security/changepassword/ChangePasswordActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/settings/security/revealmnemonic/RevealMnemonicActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/settings/tokens/TokenManagementActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/add/AddTokenActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/info/TokenInfoActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/CreateTransactionActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/ReceiptTransactionActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/ViewTransactionActivity.kt
- app/src/main/java/pm/gnosis/heimdall/utils/AppUtils.kt
- heimdall-common/src/main/java/pm/gnosis/heimdall/common/utils/AndroidUtils.kt
- Consolidate the toolbar setup methods
> WA-156: Consolidate the toolbar setup methods

- ci/release_internal_beta.sh
- gradle.properties
- Crashlytics build was failing, this PR will fix this
>  Fix assembly of crashlytics version

- app/src/main/java/pm/gnosis/heimdall/data/repositories/TransactionInfoRepository.kt
- app/src/main/java/pm/gnosis/heimdall/helpers/AddressHelper.kt
- app/src/main/java/pm/gnosis/heimdall/helpers/ToolbarHelper.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/fingerprint/FingerprintSetupActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/password/PasswordConfirmActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/password/PasswordSetupActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/create/CreateAssetTransferActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/create/CreateAssetTransferViewModel.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/review/ReviewTransactionViewModel.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/review/viewholders/AssetTransferViewHolder.kt
- app/src/test/java/pm/gnosis/heimdall/data/remote/models/push/PushMessageTest.kt
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTransactionInfoRepositoryTest.kt
- app/src/test/java/pm/gnosis/heimdall/helpers/AddressHelperTest.kt
- app/src/test/java/pm/gnosis/heimdall/helpers/ToolbarHelperTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/safe/selection/SelectSafeViewModelTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/transactions/builder/TransactionBuilderTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/transactions/create/CreateAssetTransferViewModelTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/transactions/review/ReviewTransactionViewModelTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/transactions/review/viewholders/AssetTransferViewHolderTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/transactions/review/viewholders/GenericTransactionViewHolderTest.kt
- app/src/test/java/pm/gnosis/tests/utils/TestSingleFactory.kt
Closes WA-404.
- Add test for transaction flow
> WA-404: Add test for transaction flow

- app/src/main/AndroidManifest.xml
- app/src/main/java/pm/gnosis/heimdall/di/components/ViewComponent.kt
- app/src/main/java/pm/gnosis/heimdall/reporting/EventTracker.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/SafeDetailsFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/select/SelectTokenActivity.kt
- app/src/main/res/layout/layout_safe_details.xml
- app/src/main/res/layout/layout_select_token.xml
- app/src/main/res/values/strings.xml
Closes WA-419.
- Add send button on safe detail screen
- The send button will open a new screen where the user selects the token to send.
> WA-419: Add send button and token selection

- app/src/main/java/pm/gnosis/heimdall/data/repositories/GnosisSafeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultGnosisSafeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/main/SafeMainActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/main/SafeMainContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/main/SafeMainViewModel.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/overview/SafeAdapter.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/overview/SafeOverviewContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/overview/SafeOverviewViewModel.kt
- app/src/main/res/menu/safe_details_menu.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/ui/safe/SafeOverviewViewModelTest.kt
Closes WA-423 .
- Send push on safe creation
- Add option to sync with extension 
> WA-423: Send push on safe creation. Add option to sync with extension

- app/abi/GnosisSafePersonalEdition.json
- app/build.gradle
- app/src/main/java/pm/gnosis/heimdall/data/remote/impls/LocalRelayServiceApi.kt
- buildsystem/dependencies.gradle
> Update Safe contracts

- app/src/main/java/pm/gnosis/heimdall/data/remote/models/RelayServiceData.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/pending/DeploySafeProgressFragment.kt
> Add nullable parameters to safe funded status response

- app/src/main/java/pm/gnosis/heimdall/reporting/EventTracker.kt
- app/src/main/java/pm/gnosis/heimdall/reporting/impl/FabricEventTracker.kt
- app/src/main/java/pm/gnosis/heimdall/ui/base/BaseActivity.kt
> Add firebase analytics

- app/src/main/res/layout/layout_pairing.xml
> Fix wrong constraints in Pairing Layout

- app/schemas/pm.gnosis.heimdall.data.db.ApplicationDb/1.json
- app/src/main/java/pm/gnosis/heimdall/data/db/models/GnosisSafeDb.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultGnosisSafeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTokenRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/models/Safe.kt
- app/src/main/java/pm/gnosis/heimdall/di/components/ViewComponent.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/ConfirmSafeRecoveryPhraseActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/ConfirmSafeRecoveryPhraseAdapter.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/CreateSafeIntroActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/PairingActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/SafeRecoveryPhraseActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/pending/PendingSafeContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/pending/PendingSafeFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/pending/PendingSafeViewModel.kt
- app/src/main/res/layout/layout_confirm_safe_recovery_phrase.xml
- app/src/main/res/layout/layout_confirm_transaction.xml
- app/src/main/res/layout/layout_create_safe_intro.xml
- app/src/main/res/layout/layout_pairing.xml
- app/src/main/res/layout/layout_pending_safe.xml
- app/src/main/res/layout/layout_review_transaction.xml
- app/src/main/res/layout/layout_safe_recovery_phrase.xml
- app/src/main/res/layout/layout_transaction_status.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/data/repositories/models/SafeTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/safe/list/SafeAdapterPendingViewHolderTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/safe/list/SafeAdapterViewHolderTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/safe/main/SafeMainViewModelTest.kt
- Allow any token for safe creation payment
- Fix toolbar shadow bug in multiple places
> Safe creation adjustments

- app/src/main/java/pm/gnosis/heimdall/HeimdallApplication.kt
- app/src/main/java/pm/gnosis/heimdall/data/db/daos/GnosisSafeDao.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/GnosisSafeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/ShortcutRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultGnosisSafeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultShortcutRepository.kt
- app/src/main/java/pm/gnosis/heimdall/di/components/ApplicationComponent.kt
- app/src/main/java/pm/gnosis/heimdall/di/modules/ApplicationBindingsModule.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/ConfirmSafeRecoveryPhraseViewModel.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/create/CreateAssetTransferActivity.kt
- app/src/main/res/layout/layout_create_asset_transfer.xml
- app/src/main/res/layout/layout_create_safe_intro.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/ui/safe/create/ConfirmSafeRecoveryPhraseViewModelTest.kt
- buildsystem/dependencies.gradle
Closes WA-430.
- Fix safe name reset after deploy
- Fix positioning of shadow on safe creation intro
> WA-430: Fix safe name reset after deploy

- app/src/main/java/pm/gnosis/heimdall/ui/onboarding/OnboardingIntroActivity.kt
- app/src/main/res/layout/bottom_sheet_terms_and_conditions.xml
- app/src/main/res/layout/layout_onboarding_intro.xml
- app/src/main/res/values/strings.xml
> WA-465: Update terms and conditions design/wording

- app/src/main/res/values/strings.xml
> Update Terms of Use and Privacy Policy links

- app/build.gradle
- app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingActivity.kt
- app/src/main/res/values/strings.xml
> Settings: Update Terms of Use and Privacy Policy links

- app/build.gradle
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTransactionInfoRepository.kt
- app/src/main/java/pm/gnosis/heimdall/di/modules/ApplicationModule.kt
- app/src/main/java/pm/gnosis/heimdall/ui/base/BaseActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/SafeDetailsFragment.kt
- app/src/main/java/pm/gnosis/heimdall/ui/security/unlock/UnlockActivity.kt
- app/src/main/res/layout/layout_transaction_status.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTransactionInfoRepositoryTest.kt
Closes WA-54, Fix #217 
- Add certificate pinning for safe-services and AWS root certificate 
- ERC20 transfer need to have no ether value
- Layout reference in onCreate of fragment is moved to onViewCreated
> WA-54: Added certificate pinning

- docs/CONTRIBUTING.md
- docs/ISSUE_TEMPLATE.md
I'm about to document the bug reporting process in gitlab and was reviewing the docs here. I wanted to make them a bit more idiot proof. Let me know what you think.
> Small fixes in contributing and issue template docs

- app/src/main/java/pm/gnosis/heimdall/ui/settings/general/changepassword/ChangePasswordDialog.kt
Closes #216  .
- Fix field focus when changing the password
> Fix field focus when changing the password. Closes #216

- .travis.yml
> Fix release

- app/src/main/AndroidManifest.xml
Closes #249.
- Revert Biometric permission
> Revert Biometric permission. Closes #249.

- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/CreateSafeConfirmRecoveryPhraseActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/CreateSafeConfirmRecoveryPhraseContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/CreateSafeConfirmRecoveryPhraseViewModel.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/CreateSafePairingActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/CreateSafeRecoveryPhraseIntroActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/CreateSafeSetupRecoveryPhraseActivity.kt
- app/src/main/res/layout/layout_pairing.xml
- app/src/test/java/pm/gnosis/heimdall/ui/safe/create/CreateSafeConfirmRecoveryPhraseViewModelTest.kt
See #255.
- Browser extension no longer required for safe creation
> Browser extension no longer required for safe creation. Issue #255

- buildsystem/dependencies.gradle
> Update Android Gradle build tools

- app/src/main/res/values/static_strings.xml
- app/src/main/res/values/strings.xml
- Move non translatable strings to static_strings.xml
> Move non translatable strings to static_strings.xml

- app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/safe/submit/RecoveringSafeFundFragment.kt
> Add missing view module

- .travis.yml
- ci/build_production_versions.sh
- ci/build_release_version.sh
- ci/build_rinkeby_version.sh
> Fix build upload after tag release

- app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/ConnectExtensionActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/CreateSafePairingActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionPairingActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/safe/RecoverSafePairingActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/confirm/ConfirmTransactionViewModel.kt
- app/src/main/res/layout/layout_pairing.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
- app/src/release/res/values/static_strings.xml
- app/src/test/java/pm/gnosis/heimdall/ui/transactions/view/confirm/ConfirmTransactionViewModelTest.kt
Closes #244 .
- Change `owners` to `signers`
- Change `Skip` to `Later` when connecting the browser extension
- Capitalise `Safe`
> Update string resources. Closes #244

- app/src/main/res/values-ko/strings.xml
> Update Korean localization. Add missing newlines

- app/build.gradle
- app/src/main/AndroidManifest.xml
> Remove billing dependency and missing reference in Manifest. Closes #299

- app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/viewholders/AssetTransferViewHolder.kt
> Use all the decimals when reviewing an asset transfer. Closes #297

- app/src/main/res/values-ko/strings.xml
> Update Korean localization

- app/src/main/java/pm/gnosis/heimdall/data/remote/models/push/PushMessages.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepository.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/data/remote/models/push/PushMessageTest.kt
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepositoryTest.kt
- This will show a notification when a safe was deployed
> Handle creation push

- buildsystem/dependencies.gradle
> Update Android Gradle Plugin and Kotlin version

- app/src/main/java/pm/gnosis/heimdall/data/remote/TokenServiceApi.kt
- app/src/main/res/layout/layout_manage_tokens_item.xml
- app/src/main/res/layout/layout_tokens_item_balance.xml
- Fix image scaling
- Add ordering for token endpoint
> Fix image scaling; Add ordering for token endpoint

- app/src/main/java/pm/gnosis/heimdall/data/db/daos/GnosisSafeDao.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultGnosisSafeRepository.kt
> Fix activity start after safe creation

- buildsystem/dependencies.gradle
> Update Android Gradle Plugin

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/pm/gnosis/heimdall/data/remote/models/push/PushMessages.kt
- app/src/main/java/pm/gnosis/heimdall/data/remote/models/push/ServiceMessages.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/PushServiceRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepository.kt
- app/src/main/java/pm/gnosis/heimdall/di/components/ApplicationComponent.kt
- app/src/main/java/pm/gnosis/heimdall/di/components/ViewComponent.kt
- app/src/main/java/pm/gnosis/heimdall/di/modules/ApplicationModule.kt
- app/src/main/java/pm/gnosis/heimdall/di/modules/ViewModelFactoryModule.kt
- app/src/main/java/pm/gnosis/heimdall/di/modules/ViewModule.kt
- app/src/main/java/pm/gnosis/heimdall/ui/messagesigning/ConfirmMessageActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/messagesigning/ConfirmMessageContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/messagesigning/ConfirmMessageViewModel.kt
- app/src/main/res/layout/layout_review_message.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-gl-rES/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/data/remote/models/push/PushMessageTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/addressbook/AddressBookViewModelTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/messagesigning/ConfirmMessageViewModelTest.kt
> Sign EIP712 messages sent by other Safe owners

- app/build.gradle
- app/src/main/java/pm/gnosis/heimdall/di/components/ApplicationComponent.kt
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/WalletConnectBridgeRepositoryTest.kt
- buildsystem/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- Update WalletConnect lib to 0.7
- Update Android Build Tools to 3.4.0
- Update gradle to 5.1.1
> Updated WalletConnect lib

- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/WalletConnectBridgeRepository.kt
- buildsystem/dependencies.gradle
- Update wallet connect library
> Update wallet connect library

- app/src/main/java/pm/gnosis/heimdall/data/remote/RelayServiceApi.kt
- app/src/main/java/pm/gnosis/heimdall/data/remote/models/RelayServiceData.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/CreateSafeConfirmRecoveryPhraseViewModel.kt
- app/src/test/java/pm/gnosis/heimdall/ui/safe/create/CreateSafeConfirmRecoveryPhraseViewModelTest.kt
- Update URL for PUT of funded status
- Removed code related to v1
> Update Safe creation related code

- app/src/main/java/pm/gnosis/heimdall/ui/tokens/receive/ReceiveTokenActivity.kt
- app/src/main/res/layout/layout_receive_token.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Update receive funds screen layout (#353)
- Layout change for receive funds screen
see https://github.com/gnosis/safe/tree/master/specs/receive_funds
> Update receive funds screen layout (#353)

- app/src/main/java/pm/gnosis/heimdall/data/db/ApplicationDb.kt
- app/src/main/java/pm/gnosis/heimdall/data/db/models/GnosisSafeDb.kt
Fix database schema migration
- Fix db migration when updating to 1.5.0
> Fix database schema migration

- app/schemas/pm.gnosis.heimdall.data.db.ApplicationDb/2.json
- app/src/main/java/pm/gnosis/heimdall/data/db/daos/GnosisSafeDao.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultGnosisSafeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepository.kt
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultGnosisSafeRepositoryTest.kt
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepositoryTest.kt
Fixes #392.
- Sync owners of device to notification service
- Ignore pushes for unknown Safes
- Add tests
> Fix #392: Sync owners of device to notification service

- app/build.gradle
- app/src/androidTest/java/pm/gnosis/tests/db/DbMigrationTest.kt
- buildsystem/dependencies.gradle
- test for migration from db version 1 to 2
> Add room migration test

- app/src/main/java/pm/gnosis/heimdall/ui/safe/pending/SafeCreationFundViewModel.kt
- app/src/test/java/pm/gnosis/heimdall/ui/safe/pending/SafeCreationFundViewModelTest.kt
Closes #387.
- Handle already deployed Safe on funding screen
- Retry balance check on any kind of error
> Closes #387: Handle already deployed Safe on funding screen

- README.md
- ci/upload_crashlytic_versions.sh
- docs/RELEASE.md
Closes #402
- Add release instructions
- Upload rinkeby version to beta
> Closes #402: Improve release process

- app/build.gradle
- app/src/main/java/pm/gnosis/heimdall/di/modules/ApplicationModule.kt
- buildsystem/dependencies.gradle
Add kotlin coroutines dependencies
- it is possible to write/use suspend functions now
> Add kotlin coroutines dependencies

- app/src/main/java/pm/gnosis/heimdall/data/remote/TokenServiceApi.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/TokenRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTokenRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/WalletConnectBridgeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/manage/ManageTokensActivity.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/manage/ManageTokensContract.kt
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/manage/ManageTokensViewModel.kt
- app/src/main/res/drawable/ic_close_24dp.xml
- app/src/main/res/drawable/ic_search_24dp.xml
- app/src/main/res/layout/layout_confirm_transaction.xml
- app/src/main/res/layout/layout_create_asset_transfer.xml
- app/src/main/res/layout/layout_manage_tokens.xml
- app/src/main/res/layout/layout_receive_token.xml
- app/src/main/res/layout/layout_review_message.xml
- app/src/main/res/layout/layout_select_token.xml
- app/src/main/res/layout/screen_wallet_connect_safe_selection.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTokenRepositoryTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/tokens/manage/ManageTokensViewModelTest.kt
Closes #380 .
- Add search to token management screen
> Closes #380: Add search in token management

- app/src/main/java/pm/gnosis/heimdall/data/preferences/PreferencesSafe.kt
- app/src/main/java/pm/gnosis/heimdall/data/preferences/PreferencesToken.kt
- app/src/main/java/pm/gnosis/heimdall/data/preferences/PreferencesWalletConnect.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTokenRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/WalletConnectBridgeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/di/modules/ApplicationModule.kt
- app/src/main/java/pm/gnosis/heimdall/reporting/impl/FabricCore.kt
- app/src/main/java/pm/gnosis/heimdall/services/BridgeService.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/main/SafeMainViewModel.kt
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepositoryTest.kt
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTokenRepositoryTest.kt
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/WalletConnectBridgeRepositoryIntegrationTest.kt
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/WalletConnectBridgeRepositoryTest.kt
- app/src/test/java/pm/gnosis/heimdall/ui/safe/main/SafeMainViewModelTest.kt
Closes #399: Refactor shared preferences
- encapsulate shared preferences logic & remove it from repositories
> Closes #399: Refactor wallet connect preferences

- .travis.yml
- app/src/main/java/pm/gnosis/heimdall/ui/tokens/manage/ManageTokensActivity.kt
> Closes #431: Fix back navigation in token management screen

- app/proguard-rules.pro
> Disable r8 obfuscation

- app/src/main/java/pm/gnosis/heimdall/ui/qrscan/Videographer.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/create/CreateSafePaymentTokenActivity.kt
- https://fabric.io/gnosis/android/apps/pm.gnosis.heimdall/issues/b166e0e71c8fcde1e99c62cb255dff85
- https://fabric.io/gnosis/android/apps/pm.gnosis.heimdall/issues/b913f6720d029068b9a18d4efdf71088
> Fix dappcon crashlytics crashes

- app/src/main/res/layout/bottom_sheet_address_input.xml
- app/src/main/res/values/strings.xml
Closes #443.
- Change title of address input selection dialog
> Fix #443: Change modal title

- app/src/main/java/pm/gnosis/heimdall/di/components/ViewComponent.kt
- app/src/main/java/pm/gnosis/heimdall/ui/keycard/KeycardPairingDialog.kt
- app/src/main/java/pm/gnosis/heimdall/ui/keycard/KeycardSigningDialog.kt
- app/src/main/res/layout/screen_keycard_blocked.xml
- app/src/main/res/layout/screen_keycard_no_slots.xml
- app/src/main/res/values/strings.xml
Closes #472.
- Properly handle keycard setup error states
> Closes #472: Keycard error handling

- app/build.gradle
- app/proguard-rules.pro
- app/src/main/res/layout/layout_setup_recovery_phrase.xml
- Fix bouncy castle missing in path error when connecting keycard
> Keycard hotfix: Keep bouncy castle classes

- buildsystem/dependencies.gradle
- ci/upload_crashlytic_versions.sh
- Update Crashlytics and build tools
- Fix build errors with crashlytics
> Fix master build

- app/src/main/java/pm/gnosis/heimdall/data/remote/models/push/ServiceMessages.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepository.kt
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepositoryTest.kt
Closes #485.
- Add owners that are being notified to push payload
> Closes #485: Add owners to creation push

- app/build.gradle
- app/src/main/java/pm/gnosis/heimdall/data/repositories/TransactionInfoRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTransactionInfoRepository.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/WalletConnectBridgeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/ui/safe/details/transactions/BaseTransactionViewHolder.kt
- app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/details/MultiSendDetailsActivity.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTransactionInfoRepositoryTest.kt
- Fix that some delegate calls were parsed as calls
- Fix that in some cases the multi send transctions were reordered
- Fix UI bug on multi send transaction list
- Allow restricted transactions on staging version
> Batched transactions adjustments

- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultEnsRepository.kt
- app/src/main/java/pm/gnosis/heimdall/di/modules/ApplicationBindingsModule.kt
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultEnsRepositoryTest.kt
- app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/IDNEnsNormalizerTest.kt
Closes #497.
- Normalize ENS names
> Normalize ENS name

- app/src/main/java/pm/gnosis/heimdall/data/adapters/TypeAdapters.kt
- app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/WalletConnectBridgeRepository.kt
- app/src/main/java/pm/gnosis/heimdall/di/modules/ApplicationBindingsModule.kt
- app/src/main/java/pm/gnosis/heimdall/ui/deeplinks/DeeplinkActivity.kt
- app/src/main/java/pm/gnosis/heimdall/utils/StringUtils.kt
- app/src/test/java/pm/gnosis/heimdall/ui/deeplinks/EIP681DeeplinkTransactionParserTest.kt
> Fixes for deeplink handling

- ci/prepare_env_travis.sh
- Fabric not required for travis flow
> Remove fabric from travis flow

- app/src/main/res/layout/layout_password_change_enter_old.xml
- app/src/main/res/layout/layout_password_setup.xml
Closes #526
- Add reveal button to password setup fields
> Add reveal password button to password fields

- .buildkite/deployment.yml
- ci/upload_crashlytics_versions.sh
- use buildkite env if build triggered from tag
> Fix app version issue with crashlytics upload

- app/build.gradle
- ci/upload_crashlytics_versions.sh
> Use .io endpoints

- app/build.gradle
- app/src/main/java/pm/gnosis/heimdall/data/remote/RelayServiceApi.kt
- app/src/main/res/values/strings.xml
Closes #531.
- Increase limit
- Fix string typos
> Increase limit for payment token list response

- app/build.gradle
Closes #536  .
- Update to ENS address
> Updated ENS address

- app/src/main/java/io/gnosis/safe/ui/base/BaseFragment.kt
- app/src/main/java/io/gnosis/safe/ui/base/BaseStateViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/safe/overview/SafeOverviewFragment.kt
Addressed Richard's comments that I missed before merging
> Restored base state viewModel and BaseFragment viewComponent build

- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
- data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
- Remove visible for testing
- shared prefs const are private
> Removed usage of VisibleForTesting annotation

- .buildkite/pipeline.yml
> Rename deployment trigger

- app/build.gradle
> Add test group to distribution

- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeViewModelTest.kt
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
- data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
Closes #592 .
- Added UsedSafeAddress error branch
- Added tests
- SafeRepository.isSafeAddressUsed for DAO verification
> Added safe address DAO validation with error branch and tests

- app/src/main/java/io/gnosis/safe/ui/safe/settings/app/AdvancedAppSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/settings/view/EndpointItem.kt
- app/src/main/res/layout/view_endpoint_item.xml
- app/src/main/res/values/strings.xml
- data/build.gradle
- Ripple effect for `EndpointItem` class
- Services URLs copied to clipboard
> Added URL copy to clipboard on click and ripple effect

- app/src/main/java/io/gnosis/safe/ui/safe/settings/app/AdvancedAppSettingsFragment.kt
- app/src/main/res/layout/fragment_settings_app.xml
- app/src/main/res/layout/fragment_settings_app_advanced.xml
- ~~Commented out~~ Removed `Fiat` and `Appearance` settings items 
- Removed the Relay Service from the advance app settings
> (Advanced) Settings cleanup of unused things

- app/src/main/res/color/text_button_color.xml
- app/src/main/res/drawable/toolbar_dropshadow.xml
- app/src/main/res/layout/fragment_add_safe.xml
- app/src/main/res/layout/fragment_add_safe_name.xml
- app/src/main/res/layout/toolbar_safe_overview.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- Backgrounds are white white now
- Titles in toolbars are not bolded
> More comments on style

- app/src/main/java/io/gnosis/safe/di/components/ViewComponent.kt
- app/src/main/java/io/gnosis/safe/di/modules/ViewModelFactoryModule.kt
- app/src/main/java/io/gnosis/safe/di/modules/ViewModule.kt
- app/src/main/java/io/gnosis/safe/helpers/AddressInputHelper.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/safe/assets/AssetsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/assets/AssetsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/safe/assets/AssetssFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/assets/coins/CoinBalanceAdapter.kt
- app/src/main/java/io/gnosis/safe/ui/safe/assets/coins/CoinsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/assets/coins/CoinsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/safe/assets/collectibles/CollectiblesFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/balances/coins/CoinBalanceAdapter.kt
- app/src/main/java/io/gnosis/safe/ui/safe/settings/view/EndpointItem.kt
- app/src/main/java/io/gnosis/safe/utils/BigIntegerUtils.kt
- app/src/main/java/io/gnosis/safe/utils/ImageUtils.kt
- app/src/main/res/drawable/ic_coin_placeholder.xml
- app/src/main/res/drawable/ic_qrcode_scan_white_24dp.xml
- app/src/main/res/layout/bottom_sheet_address_input.xml
- app/src/main/res/layout/fragment_settings_app_advanced.xml
- app/src/main/res/menu/bottom_nav_menu.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/safe/assets/coins/CoinsViewModelTest.kt
References:
https://github.com/gnosis/safe-android/issues/645
https://github.com/gnosis/safe-android/issues/643
https://github.com/gnosis/safe-android/issues/670
https://github.com/gnosis/safe-android/issues/609
https://github.com/gnosis/safe-android/issues/642
https://github.com/gnosis/safe-android/issues/669
- Rearranged menu items for address input
- Added on input validation of address
- Having 2 decimals for fiat currency representation of balance
- Locale aware decimal punctuation
- Renamed `Balances` to `Assets` (in class names too) 
- Added the correct placeholder for coins
> Various fixes to Balances and add safe flow

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/gnosis/safe/ui/base/BaseActivity.kt
Force day mode until dark mode is properly implemented
> Force day mode

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/helpers/AddressInputHelper.kt
- app/src/main/java/io/gnosis/safe/ui/base/BaseActivity.kt
- app/src/main/java/io/gnosis/safe/ui/base/BaseBottomSheetDialogFragment.kt
- app/src/main/java/io/gnosis/safe/ui/base/BaseFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/assets/coins/CoinsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/assets/collectibles/CollectiblesFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/empty/NoSafeFragment.kt
Track screens using firebase events
> Track screen events

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/safe/selection/SafeSelectionDialog.kt
- app/src/main/java/io/gnosis/safe/ui/safe/selection/SafeSelectionViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/safe/settings/safe/SafeSettingsViewModel.kt
- app/src/main/res/layout/dialog_safe_selection.xml
- app/src/test/java/io/gnosis/safe/ui/safe/SafeSelectionViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/safe/settings/SafeSettingsViewModelTest.kt
Fixes for:
#660 
#653
#659 
#651 
#634
- Hide safe selection icon if no safes
- Fix safe ordering: order by addition (last added safe on top), active safe on top
- Dismiss safe selection dialog when safe item selected
- Select next safe after active safe removed
- Fix scrolling issue
> Fixes safe selection issues

- app/src/main/java/io/gnosis/safe/di/modules/RepositoryModule.kt
- app/src/main/java/io/gnosis/safe/ui/safe/settings/safe/SafeSettingsViewModel.kt
- app/src/test/java/io/gnosis/safe/ui/safe/settings/SafeSettingsViewModelTest.kt
- data/src/main/java/io/gnosis/data/backend/TransactionSerivceApi.kt
- data/src/main/java/io/gnosis/data/backend/dto/SafeInfoDto.kt
- data/src/main/java/io/gnosis/data/models/SafeInfo.kt
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
- data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
Reference #664  .
- Added `SafeInfo` class containing `address` , `nonce` and `threshold`
- Added unit tests
- Added it as field in the sate for safe settings for future implementation and testing for now.
> Safe fetching

- app/src/main/java/io/gnosis/safe/ui/safe/assets/coins/CoinsViewModel.kt
- app/src/test/java/io/gnosis/safe/ui/safe/assets/coins/CoinsViewModelTest.kt
> Prevent null pointer exception when loading coins balances

- app/build.gradle
- app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt
- app/src/main/java/io/gnosis/safe/ui/transaction/TransactionView.kt
- app/src/main/java/io/gnosis/safe/ui/transaction/TransactionViewHolderFactory.kt
- app/src/main/java/io/gnosis/safe/ui/transaction/TransactionsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transaction/TransactionsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transaction/list/TransactionLoadState.kt
- app/src/main/java/io/gnosis/safe/ui/transaction/list/TransactionPagingProvider.kt
- app/src/main/java/io/gnosis/safe/ui/transaction/list/TransactionPagingSource.kt
- app/src/main/java/io/gnosis/safe/ui/transaction/list/TransactionViewListAdapter.kt
- app/src/main/res/layout/fragment_transactions.xml
- app/src/main/res/layout/item_tx_load_state.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/transaction/TransactionsViewModelTest.kt
- buildsystem/test_dependencies.gradle
- buildsystem/versions.gradle
- data/src/main/java/io/gnosis/data/backend/TransactionSerivceApi.kt
- data/src/main/java/io/gnosis/data/repositories/TransactionRepository.kt
Handles #662
- Add android paging library
- Add endpoint for loading pages of tx data
- Add data source for providing pages of tx data
- Use paging data adapter to display tx views
- Refactor tx view model to work with paging
> Implement tx list pagination using androidx paging3 lib

- app/src/main/java/io/gnosis/safe/di/components/ViewComponent.kt
- app/src/main/java/io/gnosis/safe/di/modules/ViewModelFactoryModule.kt
- app/src/main/java/io/gnosis/safe/di/modules/ViewModule.kt
- app/src/main/java/io/gnosis/safe/ui/safe/settings/safe/AdvancedSafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/settings/safe/AdvancedSafeSettingsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/safe/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/settings/safe/SafeSettingsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/safe/settings/view/LabeledAddressItem.kt
- app/src/main/java/io/gnosis/safe/ui/safe/settings/view/MasterCopyItem.kt
- app/src/main/java/io/gnosis/safe/utils/AppUtils.kt
- app/src/main/res/layout/fragment_advanced_safe_settings.xml
- app/src/main/res/layout/fragment_settings_safe.xml
- app/src/main/res/layout/view_labeled_address_item.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/safe/settings/SafeSettingsViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/safe/settings/safe/AdvancedSafeSettingsViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/transaction/TransactionsViewModelTest.kt
- buildsystem/versions.gradle
- data/src/main/java/io/gnosis/data/backend/dto/SafeInfoDto.kt
- data/src/main/java/io/gnosis/data/models/SafeInfo.kt
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
- data/src/test/java/io/gnosis/data/repositories/TransactionRepositoryTest.kt
- gradle/wrapper/gradle-wrapper.properties
Reference #594 .
- Added advanced safe settings
- Fallback handler can potentially be null, the default or unknown
- Module names are not resolved yet as it is not specified how
> Advanced Safe Settings

- app/src/main/java/io/gnosis/safe/ui/transaction/TransactionsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transaction/TransactionsViewModel.kt
force reload when pulling to refresh
> Force reload when pulling to refresh on tx list

- .buildkite/deployment.yml
- ci/upload_app_distribution.sh
Make upload script executable again
> Fix app distribution upload

- app/src/main/java/io/gnosis/safe/ui/settings/app/GetInTouchFragment.kt
- app/src/main/res/layout/fragment_get_in_touch.xml
Handles #694  
- Use custom toolbar
- White background
- Custom separators
> Align get in touch screen with design specs

- app/src/main/java/io/gnosis/safe/helpers/AddressInputHelper.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/SafeInputView.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsViewModel.kt
- app/src/main/res/drawable/background_rounded_rectangle.xml
- app/src/main/res/layout/fragment_add_safe.xml
- app/src/main/res/layout/view_safe_input.xml
- app/src/main/res/values/colors.xml
- app/src/test/java/io/gnosis/safe/ui/settings/SafeSettingsViewModelTest.kt
Reference #647 .
- Fixed small issue with error propagation to safe settings. Adjusted tests
- Added `SafeInputView` complying with the designs
> UI improvements for Add Safe address screen

- app/src/main/res/layout/view_safe_input.xml
Reference  #647 .
- removed end margin
> Removed end margin for address

- app/src/main/java/io/gnosis/safe/helpers/AddressHelper.kt
- app/src/main/java/io/gnosis/safe/ui/dialogs/EnsInputDialog.kt
- app/src/main/java/io/gnosis/safe/ui/dialogs/EnsInputViewModel.kt
- app/src/main/res/color/outline_box.xml
- app/src/main/res/drawable/cursor_drawable.xml
- app/src/main/res/layout/dialog_ens_input.xml
- app/src/main/res/layout/fragment_add_safe.xml
- app/src/main/res/layout/fragment_add_safe_name.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/io/gnosis/safe/ui/dialogs/EnsInputViewModelTest.kt
- buildsystem/versions.gradle
- data/src/main/java/io/gnosis/data/repositories/EnsRepository.kt
Reference #621  .
- Full screen ENS dialog
- Behaviour is preserved
- There are still some issues with the styling of the input field
> Full screen ENS input

- app/src/main/java/io/gnosis/safe/ui/settings/app/GetInTouchFragment.kt
> Fix email template generation

- app/proguard-rules.pro
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinBalanceAdapter.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/GetInTouchFragment.kt
- buildsystem/versions.gradle
- data/src/main/java/io/gnosis/data/adapters/MoshiBuilder.kt
- data/src/main/java/io/gnosis/data/backend/dto/ServiceBalance.kt
- data/src/main/java/io/gnosis/data/db/TypeConverters.kt
- data/src/test/java/io/gnosis/data/adapters/DataMoshiTest.kt
- data/src/test/java/io/gnosis/data/repositories/TokenRepositoryTest.kt
- data/src/test/resources/load_balances_usd.json
Handles #747 
Handles #692
- Pass data to gmail outside of intent extras due to gmail's ignorance!
- Parse balances correctly
- Add formatting pattern for ERC20 balances
> Show correct ERC20 token balances

- app/proguard-rules.pro
- buildsystem/versions.gradle
> Add proguard rules for tx list dto's

- app/src/main/java/io/gnosis/safe/ui/safe/share/ShareSafeDialog.kt
- app/src/main/res/layout/dialog_share_safe.xml
As discussed during refinement ens name field will not be shown if ens name is not set for a safe.
> Hide ens name field if not set

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt
> Prevent opening tx details till it's ready

- data/src/main/java/io/gnosis/data/backend/dto/GateTransaction.kt
- data/src/main/java/io/gnosis/data/repositories/TransactionRepository.kt
- data/src/test/java/io/gnosis/data/adapters/DataMoshiTest.kt
- data/src/test/java/io/gnosis/data/repositories/TransactionRepositoryTest.kt
Closes #780 .
- Adding tests for TransactionRepository
> Client Gateway integration tests

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- Fix crashlytics issue
https://console.firebase.google.com/u/2/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/f83f38fdb7d809f6c9d8a613a1936e93?time=last-seven-days&sessionId=5F3B93F6012500011A686931394579C9_DNE_0_v2
> Fix crash on new intent in start activity

- app/src/main/java/io/gnosis/safe/notifications/NotificationManager.kt
- app/src/main/java/io/gnosis/safe/notifications/models/PushNotification.kt
- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/res/drawable/ic_app_24dp.xml
- app/src/test/java/io/gnosis/safe/notifications/PushNotificationTest.kt
- Don't show pushes for confirmations
> Do not handle push confirmations

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxConfirmationsView.kt
- data/src/main/java/io/gnosis/data/backend/dto/GateTransactionDetails.kt
- data/src/main/java/io/gnosis/data/models/TransactionDetails.kt
- data/src/main/java/io/gnosis/data/repositories/TransactionRepository.kt
Waiting for timestamps for confirmations from client gw. Till then it's a draft 
- Fix tx confirmations list
> Fix logic for showing correct execution step

- data/build.gradle
- Adjust client gw base url for mainnet
> Adjust client gw base url for mainnet & rinkeby prod

- app/src/main/java/io/gnosis/safe/helpers/AddressHelper.kt
- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/safe/selection/SafeSelectionAdapter.kt
- app/src/main/java/io/gnosis/safe/ui/settings/view/AddressItem.kt
- app/src/main/java/io/gnosis/safe/ui/settings/view/LabeledAddressItem.kt
- app/src/main/java/io/gnosis/safe/ui/settings/view/MasterCopyItem.kt
- app/src/main/java/io/gnosis/safe/utils/StringUtils.kt
> Display addresses as 0xffff...ffff

- app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt
- app/src/main/java/io/gnosis/safe/notifications/NotificationManager.kt
- app/src/main/java/io/gnosis/safe/notifications/NotificationRepository.kt
- app/src/main/java/io/gnosis/safe/ui/splash/SplashActivity.kt
> Track push_info

- app/src/main/java/io/gnosis/safe/notifications/NotificationManager.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinBalanceAdapter.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsFragment.kt
- app/src/main/res/values/strings.xml
> Show amount for incoming eth notifications

- app/src/main/java/io/gnosis/safe/notifications/NotificationManager.kt
- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
> Fix navigation after receiving push notification

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
> Update tx list when navigating to tx list page

- app/src/main/java/io/gnosis/safe/notifications/models/PushNotification.kt
- app/src/test/java/io/gnosis/safe/notifications/PushNotificationTest.kt
> Fix parsing of  incoming ERC721 notification

- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxConfirmationsView.kt
- app/src/main/res/values/strings.xml
> Change spelling: Canceled -> Cancelled

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
> Show spinner when reloading data for tx list

- app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt
- app/src/main/java/io/gnosis/safe/notifications/NotificationRepository.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeNameViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/splash/SplashActivity.kt
- app/src/main/java/io/gnosis/safe/ui/splash/SplashViewModel.kt
- app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeNameViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/settings/SafeSettingsViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/splash/SplashViewModelTest.kt
- data/src/main/java/io/gnosis/data/db/daos/SafeDao.kt
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
Handles #854
- Check and set user properties on app start
> Set user properties on app start

- ci/upload_app_distribution.sh
> Fix setting app version for tagged builds

- ci/notify_slack.sh
- Fix release url in slack notification
> Fix slack notification

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionView.kt
- app/src/main/java/io/gnosis/safe/utils/TxUtils.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
- data/src/main/java/io/gnosis/data/backend/dto/GateTransaction.kt
- data/src/main/java/io/gnosis/data/models/Transaction.kt
- data/src/main/java/io/gnosis/data/models/TransactionDetails.kt
- data/src/main/java/io/gnosis/data/repositories/TransactionRepository.kt
- data/src/test/java/io/gnosis/data/repositories/TransactionRepositoryTest.kt
Closes #847  .
- Adds creation tx to the end of the tx list
> Adds creation tx to tx list

- app/src/main/java/io/gnosis/safe/di/components/ApplicationComponent.kt
- app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt
- app/src/main/java/io/gnosis/safe/notifications/NotificationManager.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinBalanceAdapter.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/utils/BalanceFormatter.kt
- app/src/main/java/io/gnosis/safe/utils/BigIntegerUtils.kt
- app/src/main/java/io/gnosis/safe/utils/TxUtils.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
- app/src/test/java/io/gnosis/safe/utils/BalanceFormatterTest.kt
- app/src/test/java/io/gnosis/safe/utils/TxUtilsKtTest.kt
Handles #689 
Handles #762 
- Add balance formatter
- Use short amount on coins screen
- Use short amount string in tx list
- Use short amount string on tx details screen
https://github.com/gnosis/safe/wiki/How-to-format-amounts
https://gnosisinc.slack.com/archives/C63LQTGNB/p1599485682208500?thread_ts=1599482003.203700&cid=C63LQTGNB
> Format amounts

- app/src/main/java/io/gnosis/safe/di/components/ViewComponent.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/view/MasterCopyItem.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionView.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/AdvancedTransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/CreationTransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxStatusView.kt
- app/src/main/res/layout/fragment_transaction_details_creation.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
> Creation tx details

- app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt
- app/src/main/java/io/gnosis/safe/utils/BalanceFormatter.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
- app/src/test/java/io/gnosis/safe/utils/BalanceFormatterTest.kt
- app/src/test/java/io/gnosis/safe/utils/TxUtilsKtTest.kt
> Fix formatting rules for balances

- app/src/main/java/io/gnosis/safe/utils/AppUtils.kt
- app/src/main/res/values/strings.xml
> Show connection timeout errors

- app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt
> Increase connection, read and write timeouts to 30 seconds

- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/details/CollectiblesDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/view/LabeledAddressItem.kt
- app/src/main/res/layout/item_collectible_collectible.xml
Handles #886 
Handles #889
Handles #894 
- Make shadow on top of collectible list item more visible
- Copy address to clipboard on click for LabeledAddressItem
- Hide view on token link on collectible details page
> Fix collectible issues

- data/src/main/java/io/gnosis/data/repositories/TokenRepository.kt
- data/src/test/java/io/gnosis/data/repositories/TokenRepositoryTest.kt
- data/src/test/resources/load_collectibles.json
Handles #885
- Sort groups alphabetically
- Sort collectibles in groups alphabetically
- Put `unknown` elements at the end of the list
> Fix sorting for collectible list

- app/src/main/res/layout/fragment_transaction_list.xml
> Hide progress indicator if no loading in progress

- app/src/main/java/io/gnosis/safe/utils/BalanceFormatter.kt
- app/src/test/java/io/gnosis/safe/utils/BalanceFormatterTest.kt
> Cut off amount decimals instead of rounding

- app/src/main/res/layout/fragment_transaction_details_creation.xml
> Set background color of the tx creation screen to white

- app/src/main/java/io/gnosis/safe/helpers/ConnectivityInfoProvider.kt
> Improve connectivity info provider

- .github/ISSUE_TEMPLATE/bug_report.md
> Add environment section to bug template

- data/src/main/java/io/gnosis/data/backend/dto/TransactionDto.kt
- data/src/main/java/io/gnosis/data/repositories/TransactionRepository.kt
> Workaround for crash because of polymorphic param data

- app/src/main/res/layout/item_coin_balance.xml
> Adjust layout for coin balance items

- buildsystem/versions.gradle
> Remove wallet connect dependency

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- data/src/main/java/io/gnosis/data/backend/dto/TransactionDto.kt
Regarding #817 .
- Add displayName to Operation and use it
> Add displayName() to Operation enum

- app/build.gradle
- app/src/main/java/io/gnosis/safe/helpers/AddressInputHelper.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeNameFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/utils/DialogBuilders.kt
- app/src/main/res/layout/bottom_sheet_address_input.xml
- app/src/main/res/layout/layout_alert_dialog_title.xml
Closes #789 .
- Disable Synthetics
- Convert remaining usages to ViewBindings 
- Housekeeping
> Disable synthetics

- app/build.gradle
- app/src/main/java/io/gnosis/safe/ui/settings/view/MasterCopyItem.kt
Handles #911 
- Copy address to clipboard on click
- Disable leak canary
> Make address copiable to clipboard for MasterCopyItem

- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
> Explicitly set string res for cancel button of safe removal dialog

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/main/java/io/gnosis/safe/utils/TxUtils.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
- app/src/test/java/io/gnosis/safe/utils/TxUtilsKtTest.kt
- data/src/main/java/io/gnosis/data/repositories/TokenRepository.kt
Regarding #800 .
- Sometimes we do not have a symbol for ERC721 or ERC20 tokens. Then we show NFT or ERC20 as a default symbol
- 
- 
> Default NFT/ERC20 symbol

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt
> Grey out label for canceled transaction

- docs/RELEASE.md
> Update release process description

- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxDataView.kt
- app/src/main/res/values/strings.xml
> Copy data to clipboard when clicked

- app/src/main/java/io/gnosis/safe/ui/settings/owner/ImportOwnerKeyViewModel.kt
- app/src/test/java/io/gnosis/safe/ui/settings/owner/ImportOwnerKeyViewModelTest.kt
Handles #947 
- One commit missing to make the solution case insensitive.
> Ignore casing of words in seed phrase

- app/src/main/java/io/gnosis/safe/ui/settings/app/AppSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/utils/AppUtils.kt
- app/src/main/res/layout/dialog_remove.xml
- app/src/main/res/values/strings.xml
Handles #951
- Extract remove dialog to app utils
- Add confirmation dialog for removing owner key
> Add remove owner confirmation dialog

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/di/components/ViewComponent.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionMultisendFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/MultisendActionView.kt
- app/src/main/res/layout/fragment_transaction_details_action_multisend.xml
- app/src/main/res/layout/view_multisend_action.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
- Add custom view for multisend action item
- Extend nav graph
> Show decoded multisend data

- app/src/main/java/io/gnosis/safe/ui/settings/app/AppSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
- app/src/main/java/io/gnosis/safe/utils/AppUtils.kt
- app/src/main/res/layout/fragment_transaction_details.xml
- app/src/main/res/values/strings.xml
Handles #954 
- Added button for confirm tx to the UI
> Added tx confirm button to the UI

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
- data/src/main/java/io/gnosis/data/backend/dto/GateTransactionDetails.kt
- data/src/main/java/io/gnosis/data/models/TransactionDetails.kt
- data/src/main/java/io/gnosis/data/repositories/TransactionRepository.kt
- data/src/main/java/io/gnosis/data/utils/SafeTxHash.kt
- data/src/test/java/io/gnosis/data/utils/SafeTxHashTest.kt
- data/src/test/resources/tx_details_custom.json
- data/src/test/resources/tx_details_settings_change.json
- data/src/test/resources/tx_details_transfer.json
Handles #957
- Calculate safe tx hash
- Compare calculated hash with hash returned by backend
> Add safe tx hash validation

- app/build.gradle
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/LabeledArrayItem.kt
- app/src/main/res/layout/fragment_settings_app.xml
- app/src/main/res/layout/item_tx_change_mastercopy.xml
- app/src/main/res/layout/item_tx_queued_change_mastercopy.xml
- app/src/main/res/layout/item_tx_queued_transfer.xml
- app/src/main/res/layout/item_tx_transfer.xml
- app/src/main/res/layout/view_labeled_array_item.xml
- data/src/main/java/io/gnosis/data/backend/dto/TransactionDto.kt
> Release 2.3.0

- app/src/main/res/layout/fragment_settings_app.xml
> Show owner key in app settings

- data/build.gradle
> Fix typo in client gw service urls

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
> Show awaiting your confirmation on tx details page

- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeViewModel.kt
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
- data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
Handles #996
- Prevent errors from being swallowed in the view model
- Show correct error in snack bar
> Fix error handling when adding safe

- app/build.gradle
- app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt
- buildsystem/constants.gradle
Handles #955
- Use map for pins 
- Clean up unsused domains & pins
> Clean up ssl pinning

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/AppSettingsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerSelectionViewModel.kt
Handles #1020
- Add user property
- set user property on storage and removal of owner 
> Track num_keys_imported

- app/src/main/java/io/gnosis/safe/di/modules/InterceptorsModule.kt
- buildsystem/versions.gradle
Handles #602 
- Upgrade version
- Fix deprecation error
> Upgrade okhttp version to 4

- app/src/main/java/io/gnosis/safe/utils/TxUtils.kt
- app/src/test/java/io/gnosis/safe/utils/TxUtilsKtTest.kt
Handles #959
- Fixed formatter for custom tx
- Added regression test
-
> Custom tx details amount should be negative

- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsViewModel.kt
- app/src/main/res/values/strings.xml
Handles #866 #1021 
- Copy for splash screen changed according to #1021 
- Loading state triggers on safe load #866 
> Copy update/ Loading state SafeSettings

- app/build.gradle
- Add valid pin to gnosisdev domain
> Update ssl pinning

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxStatusView.kt
- app/src/main/res/layout/view_tx_status.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
> Fix tx status layout

- app/build.gradle
- app/src/main/java/io/gnosis/safe/ui/settings/app/AppSettingsFragment.kt
> Release 2.4.0

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
> Handle errors when loading tx list

- .buildkite/deployment.yml
- app/build.gradle
- buildsystem/android_library.gradle
- data/build.gradle
> Add flavor for mainnet staging

- app/src/main/java/io/gnosis/safe/HeimdallApplication.kt
> Add crash reporting timber tree

- app/build.gradle
- data/build.gradle
> Fix typo in mainnet staging tx service url

- app/proguard-rules.pro
> Adjust proguard rules

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
> Reload tx list after navigation to other tabs

- app/src/main/java/io/gnosis/safe/helpers/AddressInputHelper.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeNameFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/SafeInputView.kt
- app/src/main/java/io/gnosis/safe/utils/StringUtils.kt
- app/src/main/res/layout/dialog_ens_input.xml
- app/src/main/res/layout/fragment_add_safe_name.xml
- app/src/main/res/layout/view_safe_input.xml
- app/src/main/res/values/strings.xml
> Show invalid input when adding safe

- app/src/main/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsFragment.kt
Handles #1051
- Special handling for Offline error
> Error on the safe setting->advanced page when no internet connection

- app/src/main/res/layout/view_endpoint_item.xml
> Don't truncate endpoint urls

- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsViewModel.kt
> Fix safe settings loading & error handling

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
> Show data cannot be loaded for tx list & details placeholder when data could not be loaded

- app/src/main/java/io/gnosis/safe/ErrorHandler.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesFragment.kt
- app/src/main/java/io/gnosis/safe/ui/dialogs/EnsInputDialog.kt
- app/src/main/java/io/gnosis/safe/ui/dialogs/EnsInputViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeNameFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerSeedPhraseFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
- app/src/main/java/io/gnosis/safe/utils/AppUtils.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/values/values.xml
- app/src/test/java/io/gnosis/safe/ui/dialogs/EnsInputViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModelTest.kt
- data/src/main/java/io/gnosis/data/repositories/EnsRepository.kt
Handles #842
https://docs.google.com/document/d/1foQ9DSMgO2iN-6u4JsJIDJWB7mUHX-D8ApZWvx6oKAo/edit#
- Introduce new error classes
- Map exceptions to errors
- Show error messages using the new format
> Use new format for errors

- app/src/main/java/io/gnosis/safe/ui/transactions/details/AdvancedTransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/res/layout/fragment_transaction_details_advanced.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
Handles #1101
- Show safeTxHash in TransactionDetailFragment
> Pass safeTxHash to Advanced TransactionDetailFragment and show it.

- app/src/main/java/io/gnosis/safe/ErrorHandler.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerSeedPhraseViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
- app/src/main/res/layout/view_safe_input.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/settings/owner/ImportOwnerKeyViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModelTest.kt
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
- data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
- qrscanner/src/main/res/values/string.xml
Handles #1109 
Handles #1110 
Handles #1116
Handles #1117
Handles #1118
Handles #1119
> Handle safe not found error; check implementation copy before adding safe; minor layout fixes

- app/src/main/java/io/gnosis/safe/ErrorHandler.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
> Use custom snackbar builder with increased display duration for errors

- app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt
- app/src/main/java/io/gnosis/safe/notifications/NotificationManager.kt
- app/src/main/java/io/gnosis/safe/notifications/NotificationRepository.kt
- app/src/main/java/io/gnosis/safe/notifications/NotificationServiceApi.kt
- app/src/main/java/io/gnosis/safe/notifications/models/PushNotification.kt
- app/src/main/java/io/gnosis/safe/notifications/models/Registration.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/AppSettingsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerSelectionViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/notifications/PushNotificationTest.kt
- app/src/test/java/io/gnosis/safe/notifications/RegistrationTest.kt
- app/src/test/java/io/gnosis/safe/ui/settings/owner/OwnerSelectionViewModelTest.kt
- data/src/main/java/io/gnosis/data/repositories/TransactionRepository.kt
- data/src/main/java/io/gnosis/data/utils/SignatureUtils.kt
Handles #1079
- Add notification type for a confirmation request 
- Calculate signatures for owners
- Generate uuid for device registration
> Push notifications for signing transactions

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/res/layout/fragment_settings_app_advanced.xml
- app/src/main/res/values/styles.xml
> React to notifications only for safes stored on device

- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsViewModel.kt
- app/src/test/java/io/gnosis/safe/ui/settings/SafeSettingsViewModelTest.kt
> Fix safe removal

- app/build.gradle
- app/src/main/java/io/gnosis/safe/notifications/models/Registration.kt
- data/build.gradle
- data/src/main/java/io/gnosis/data/adapters/MoshiBuilder.kt
- data/src/main/java/io/gnosis/data/models/Page.kt
- data/src/main/java/io/gnosis/data/models/assets/Collectible.kt
- data/src/main/java/io/gnosis/data/models/transaction/DataDecoded.kt
- data/src/main/java/io/gnosis/data/models/transaction/SettingsInfo.kt
- data/src/main/java/io/gnosis/data/models/transaction/Transaction.kt
- data/src/main/java/io/gnosis/data/models/transaction/TransactionConfirmationRequest.kt
- data/src/main/java/io/gnosis/data/models/transaction/TransactionDetails.kt
- data/src/main/java/io/gnosis/data/models/transaction/TransactionInfo.kt
- data/src/main/java/io/gnosis/data/models/transaction/TransferInfo.kt
- data/src/main/java/io/gnosis/data/models/transaction/TxListEntry.kt
- data/src/test/java/io/gnosis/data/repositories/TokenRepositoryTest.kt
> Don't rely on reflection for property names for json parsing

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
Handles #1160 
- Prevent endless reload
> Endless reload prevented

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
- app/src/main/res/layout/item_tx_conflict_section_header.xml
- app/src/main/res/layout/item_tx_conflict_tx.xml
- app/src/main/res/layout/item_tx_contract_interaction.xml
- app/src/main/res/layout/item_tx_queued_contract_interaction.xml
Handles #1161 
- "Contract interaction" should not be ellipsized
- Wrapped link icon outside header
- Missing seperator afte last conflict element
- Grey line not aligned with tx type icon
Conflicts | The Rest 
--------  | ---------
> Queue list UI fixes

- app/src/main/java/io/gnosis/safe/helpers/ConnectivityInfoProvider.kt
- buildsystem/versions.gradle
- gradle/wrapper/gradle-wrapper.properties
> Fix offline handling

- app/src/main/res/layout/fragment_get_in_touch.xml
> Fix wrong background color for get in touch screen in night mode

- app/src/main/java/io/gnosis/safe/utils/ImageUtils.kt
> Fix coin icons placeholder

- app/src/main/res/layout/dialog_ens_input.xml
- app/src/main/res/layout/fragment_collectibles_details.xml
- app/src/main/res/layout/fragment_owner_seed_phrase.xml
- app/src/main/res/layout/fragment_settings_app_night_mode.xml
- app/src/main/res/layout/fragment_settings_safe_advanced.xml
- app/src/main/res/layout/fragment_settings_safe_edit_name.xml
- app/src/main/res/layout/fragment_transaction_details_action.xml
- app/src/main/res/layout/fragment_transaction_details_action_multisend.xml
- app/src/main/res/layout/fragment_transaction_details_advanced.xml
Handles #1145 
Action details
Light | Dark
----- | -----
Multisend details
Light | Dark
----- | -----
Appearance
Light | Dark
----- | -----
Advanced tx details
Light | Dark
----- | -----
Edit safe name
Light | Dark
----- | -----
Advanced safe settings
Light | Dark
----- | -----
Collectibles details
Light | Dark
----- | -----
Enter ENS name
Light | Dark
----- | -----
Import owner key
Light | Dark
----- | -----
> Screen background colors

- app/src/main/res/layout/fragment_transaction_details_action.xml
> Fix toolbar for multisend details

- app/src/main/res/layout/view_tx_amount.xml
> Fix long token name on tx details

- app/src/main/res/layout/fragment_collectibles_details.xml
> Set collectible image background to white for details

- app/src/main/java/io/gnosis/safe/utils/StringUtils.kt
- app/src/main/res/values/static_strings.xml
- contracts/build.gradle
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
> Recognize Safe contracts implementation v1.2.0

- app/src/main/java/io/gnosis/safe/ui/settings/app/AppSettingsFragment.kt
> Copy owner address to clipboard when clicked

- app/src/main/res/values/strings.xml
> Adjust toolbar title for import owner flow

- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeOwnerFragment.kt
> Add callbacks to copy safe address to clipboard & open etherscan on add safe owner screen

- app/src/main/java/io/gnosis/safe/utils/BalanceFormatter.kt
- app/src/test/java/io/gnosis/safe/utils/BalanceFormatterTest.kt
> Use defined number formatting for fiat balances

- app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerSeedPhraseFragment.kt
- app/src/main/res/layout/fragment_owner_seed_phrase.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Handles #1191
Text update according to design: https://zpl.io/VxNo8zW
> Text and margin updated

- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesFragment.kt
- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
Handles #1210 
Handles #1215 
Handles #1216
> Reload content on opening

- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesFragment.kt
- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeOwnerFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerSeedPhraseFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
- app/src/main/java/io/gnosis/safe/utils/BalanceFormatter.kt
- app/src/main/res/layout/fragment_owner_seed_phrase.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/utils/BalanceFormatterTest.kt
> Add recent fixes to rc

- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
- app/src/test/java/io/gnosis/safe/utils/TxUtilsKtTest.kt
- data/src/main/java/io/gnosis/data/models/AddressInfo.kt
- data/src/main/java/io/gnosis/data/models/transaction/SettingsInfo.kt
- data/src/main/java/io/gnosis/data/models/transaction/TransactionInfo.kt
- data/src/test/java/io/gnosis/data/adapters/DataMoshiTest.kt
- data/src/test/java/io/gnosis/data/repositories/TransactionRepositoryTest.kt
- data/src/test/resources/custom.json
- data/src/test/resources/settings_change.json
- data/src/test/resources/transfer_erc20.json
- data/src/test/resources/tx_details_custom.json
> Add *Infos to transfers, setting changes and custom transactions

- app/build.gradle
- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/AppSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/SettingsHandler.kt
- app/src/main/res/layout/fragment_settings_app.xml
- app/src/main/res/values/strings.xml
- buildsystem/versions.gradle
Handles #1206 
Handles #1207
- Add app settings menu leading to playstore for user to leave a review
- Start in-app review flow if conditions apply
- on 3rd start not counting navigation from push notifications
- google policies control whether the in-app review dialog will be shown
> Add in-app review flow

- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsAdapter.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeOwnerFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/empty/NoSafeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/selection/SafeSelectionViewModel.kt
- app/src/main/res/layout/fragment_transactions.xml
- app/src/main/res/navigation/main_nav.xml
Handles #1242
- Make owner import flow global action to allow navigation from different starting points (Assets, Tx's, Settings)
> Fix navigation to import owner flow

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionView.kt
- app/src/main/res/layout/item_tx_contract_interaction.xml
- app/src/main/res/layout/item_tx_queued_contract_interaction.xml
- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
> Show known address names in tx list

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxStatusView.kt
- app/src/main/res/layout/item_tx_queued_contract_interaction.xml
- app/src/main/res/layout/item_tx_queued_settings_change.xml
- app/src/main/res/layout/item_tx_queued_transfer.xml
- app/src/main/res/layout/view_tx_status.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
Handles #1266 
- Change display Strings
- Cange variable names
- Keep enum names (?)
> Change Strings and rename variables. Omit enums.

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
Handles #1284 
- Update ui for real
> Hotfix: TX details not updated after confirmation

- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerSelectionViewModel.kt
> Prevent missing registration request when adding owner

- app/src/main/java/io/gnosis/safe/Tracker.kt
> Adjust rejection confirmation screen tracking

- app/build.gradle
> Release 2.11.0

- app/src/main/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt
Handles #1250 
Old  | New
--- | ---
> Fixed icon for fallbackHandler link and conflict link

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/res/layout/fragment_transaction_details.xml
Handles #1302
https://user-images.githubusercontent.com/246473/110617616-2cb3f200-8196-11eb-876d-faae7342108f.mp4
> Rejection button overlaps details

- app/src/main/res/values/strings.xml
Handles #1305 
- Fixed error message
> implementation -> master

- .github/workflows/cla.yml
> Add CLA to repository

- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/view/MasterCopyItem.kt
- app/src/main/res/layout/view_mastercopy_item.xml
> Load logo for master copy in safe settings

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/di/components/ViewComponent.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/DisablePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/EnterPasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/RepeatPasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
- app/src/main/res/navigation/main_nav.xml
- app/src/test/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModelTest.kt
- data/src/main/java/io/gnosis/data/repositories/CredentialsRepository.kt
> Add enter passcode screen. Require passcode input before tx confirmation

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/di/components/ViewComponent.kt
- app/src/main/java/io/gnosis/safe/ui/base/SafeOverviewBase.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeCreatePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangePasscodeViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeRepeatPasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/CreatePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/DisablePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/EnterPasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/RepeatPasscodeFragment.kt
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
> Change Passcode

- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangePasscodeViewModel.kt
Handles #1276
- Fixes delete owner keys check
> Fixes delete owner keys check

- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeCreatePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeRepeatPasscodeFragment.kt
Handles #
- Override back button to skip flow.
> Handle back button correctly in change password flow.

- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeCreatePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeRepeatPasscodeFragment.kt
> Fix screen title

- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsAdapter.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt
- app/src/main/res/navigation/main_nav.xml
> Fix passcode banner

- app/src/main/java/io/gnosis/safe/ui/settings/owner/intro/InfoItemView.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/intro/OwnerInfoFragment.kt
- app/src/main/res/layout/fragment_owner_info.xml
- app/src/main/res/values/static_strings.xml
- app/src/main/res/values/strings.xml
> Educate users about how private key is stored

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
> Fix confirm button still available after tx confirmation

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt
> Fix issue #1331: no logo for the safe app with svg logo

- app/src/main/res/navigation/main_nav.xml
> Fix passcode banner crash

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
Handles #1386
- Use updated executionInfo to render Button
> Fix confirm button

- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
> Fix safe settings ui reload

- app/src/main/java/io/gnosis/safe/ui/settings/app/fiat/AppFiatFragment.kt
- app/src/main/res/layout/fragment_app_fiat.xml
> Add data cannot be loaded placeholder to fiat list screen

- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionView.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/CreationTransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxConfirmationsView.kt
- app/src/main/res/navigation/main_nav.xml
- app/src/test/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModelTest.kt
> Show owner key names in safe settings & tx confirmations

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/safe/selection/SafeSelectionDialog.kt
- app/src/main/java/io/gnosis/safe/ui/safe/selection/SafeSelectionViewModel.kt
- app/src/main/res/layout/toolbar_safe_overview.xml
- app/src/main/res/values/strings.xml
> Check if safe can confirm/reject tx and show read-only label in toolbar

- app/build.gradle
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListAdapter.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
- app/src/main/res/layout/item_owner_local.xml
Handles #
- Contains fixes made for the release
- Crash when deleting keys
- Use updated `updatedExecutionInfo`
- and more :-)
> Release 2.14.0 -> master

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerEditNameViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerEnterNameViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListViewModel.kt
- app/src/test/java/io/gnosis/safe/ui/settings/owner/OwnerEnterNameViewModelTest.kt
Handles #1387
- Track when a key is imported
- Track actual number of imported owners
-
> Track key removal. Fix number of keys imported

- app/src/main/java/io/gnosis/safe/ui/transactions/details/ButtonStateHelper.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/viewdata/TransactionDetailsViewData.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/details/ButtonStateHelperTest.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModelTest.kt
Handles #1386, #1371
- Complete rewrite of ButtonStateHelper
- Tests adapted to scenarios in https://docs.google.com/document/d/13GirjSwieQaqUPz-8HXzJP_rfgmobSp7E4TpbnLlb0M/edit#bookmark=id.3cvx2oq4xmgz
> ButtonStateHelper rewrite

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
> Fail silently if read-only check cannot be performed

- app/src/main/java/io/gnosis/safe/helpers/ConnectivityInfoProvider.kt
- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/SigningOwnerSelectionFragment.kt
- app/src/main/java/io/gnosis/safe/utils/AppUtils.kt
- app/src/main/res/drawable/background_input.xml
- app/src/main/res/drawable/button_confirm.xml
- app/src/main/res/drawable/button_primary.xml
- app/src/main/res/drawable/button_reject.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
- build.gradle
- qrscanner/src/main/java/io/gnosis/safe/qrscanner/Videographer.kt
> Adjust colors for confirm/reject/primary buttons

- app/src/main/java/io/gnosis/safe/ui/base/activity/BaseActivity.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/AdvancedAppSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/SettingsHandler.kt
- app/src/main/java/io/gnosis/safe/ui/splash/SplashActivity.kt
- app/src/main/java/io/gnosis/safe/ui/splash/SplashViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/terms/TermsBottomSheetDialog.kt
- app/src/main/res/layout/bottom_sheet_terms_and_conditions.xml
- app/src/main/res/layout/fragment_settings_app_advanced.xml
- app/src/main/res/values/static_strings.xml
- app/src/main/res/values/strings.xml
Handles #1378 
- Change Button on terms sheet to disable tracking
- Add Tracking setting item in advanced app settings
- Add crash trigger for staging apps in advanced app settings
> Disable tracking

- app/src/main/java/io/gnosis/safe/di/modules/RepositoryModule.kt
- buildsystem/versions.gradle
- data/src/main/java/io/gnosis/data/repositories/DummyDomainResolution.kt
- data/src/main/java/io/gnosis/data/repositories/UnstoppableDomainsRepository.kt
- data/src/main/java/io/gnosis/data/utils/ExcludeClassFromJacocoGeneratedReport.kt
Handles #1398
- Add crash protection gaianst UD lib initilization
- Add way to exclude classes from code coverage with an annotation
- Increase UD version
> Hotfix: Crash in unstoppable domains 

- app/src/main/res/layout/bottom_sheet_address_input.xml
> Disable UD

- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeCreatePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeRepeatPasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/CreatePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/DisablePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/EnterPasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeUtils.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/RepeatPasscodeFragment.kt
Handles #1407
- delay show keyboard 
-
-
> Delay showKeyboard by 200ms

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionFragment.kt
- app/src/main/res/navigation/main_nav.xml
- data/src/main/java/io/gnosis/data/models/transaction/DataDecoded.kt
Handles #1417
- Change DTO
- change rendering 
> data is optional

- app/src/main/java/io/gnosis/safe/utils/SemVer.kt
- app/src/test/java/io/gnosis/safe/utils/SemVerTest.kt
> Adjust range separator to '...' 

- app/src/main/java/io/gnosis/safe/ui/settings/app/SettingsHandler.kt
- app/src/main/java/io/gnosis/safe/utils/SemVer.kt
- app/src/test/java/io/gnosis/safe/ui/dialogs/EnsInputViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeNameViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/safe/share/ShareSafeViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/settings/SafeSettingsViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/settings/safe/SafeSettingsEditNameViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/splash/SplashViewModelTest.kt
- app/src/test/java/io/gnosis/safe/utils/SemVerTest.kt
- data/src/androidTest/java/io/gnosis/data/db/HeimdallDatabaseTest.kt
- data/src/test/java/io/gnosis/data/repositories/EnsRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/TokenRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/TransactionRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/UnstoppableRepositoryTest.kt
- data/src/test/java/io/gnosis/data/security/HeimdallEncryptionManagerTest.kt
> Ignore sem ver extensions when comparing remote config values

- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/LabeledArrayItem.kt
> Fix rendering of nested arrays of mixed type

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/AdvancedAppSettingsFragment.kt
- app/src/main/res/layout/fragment_settings_app_advanced.xml
> Fix passcode reset on update

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
> Require for confirmations is true after upgrade

- app/build.gradle
- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/AdvancedAppSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/SettingsHandler.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/LabeledArrayItem.kt
- app/src/main/java/io/gnosis/safe/utils/SemVer.kt
- app/src/main/res/layout/fragment_settings_app_advanced.xml
- app/src/test/java/io/gnosis/safe/ui/dialogs/EnsInputViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeNameViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/safe/share/ShareSafeViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/settings/SafeSettingsViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/settings/safe/SafeSettingsEditNameViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/splash/SplashViewModelTest.kt
- app/src/test/java/io/gnosis/safe/utils/SemVerTest.kt
- data/src/androidTest/java/io/gnosis/data/db/HeimdallDatabaseTest.kt
- data/src/test/java/io/gnosis/data/repositories/EnsRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/TokenRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/TransactionRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/UnstoppableRepositoryTest.kt
- data/src/test/java/io/gnosis/data/security/HeimdallEncryptionManagerTest.kt
> Release 2.16.0

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/di/components/ViewComponent.kt
- app/src/main/java/io/gnosis/safe/di/modules/ViewModelFactoryModule.kt
- app/src/main/java/io/gnosis/safe/di/modules/ViewModule.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerEnterNameFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/details/OwnerDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/details/OwnerDetailsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListFragment.kt
- app/src/main/res/layout/fragment_owner_details.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/settings/owner/details/OwnerDetailsViewModelTest.kt
> Add owner key details screen

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/di/modules/ViewModelFactoryModule.kt
- app/src/main/java/io/gnosis/safe/di/modules/ViewModule.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerEditNameViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerEnterNameFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerEnterNameViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/details/OwnerDetailsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/intro/OwnerGenerateViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/intro/OwnerInfoGenerateFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListAdapter.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/selection/OwnerSelectionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/splash/SplashViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/SigningOwnerSelectionFragment.kt
- app/src/main/res/layout/fragment_owner_list.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/settings/owner/OwnerEnterNameViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/settings/owner/details/OwnerDetailsViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/splash/SplashViewModelTest.kt
- data/src/main/java/io/gnosis/data/db/HeimdallDatabase.kt
- data/src/main/java/io/gnosis/data/db/daos/OwnerDao.kt
- data/src/main/java/io/gnosis/data/models/Owner.kt
- data/src/main/java/io/gnosis/data/repositories/CredentialsRepository.kt
Handles #1448
Handles #1474
- Generate mnemonic & keys
- Store mnemonic for generated key as encrypted string in a database
- Separate tracking for imported & generated keys
> Generate owner locally

- buildsystem/versions.gradle
- data/src/main/java/io/gnosis/data/db/HeimdallDatabase.kt
- data/src/main/java/io/gnosis/data/models/Owner.kt
- data/src/main/java/io/gnosis/data/repositories/CredentialsRepository.kt
- Use NullableConverters for ExcrypteVyteArray and EncryptedString
> Using NullableConverters

- app/src/main/java/io/gnosis/safe/ui/base/SafeOverviewBase.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/SettingsHandler.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/EnterPasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/details/OwnerDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/details/OwnerDetailsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListFragment.kt
- app/src/main/res/layout/fragment_settings_app_passcode.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/settings/owner/details/OwnerDetailsViewModelTest.kt
Handles #1453
- New setting item in passcode settings
- New flags in settings handler
- No export without passcode if option is enabled
- Adjust navigation
> Protect owner key export with passcode

- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsAdapter.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsViewData.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeOwnerFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerEnterNameFragment.kt
- app/src/main/res/layout/fragment_add_safe_owner.xml
- app/src/main/res/layout/fragment_owner_name_enter.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
- data/src/main/java/io/gnosis/data/repositories/CredentialsRepository.kt
- data/src/test/java/io/gnosis/data/repositories/CredentialsRepositoryTest.kt
> Cherry picked from master for release

- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/RepeatPasscodeFragment.kt
> Update passcode decrypted by biometric key

- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt
Handles #1503
- Encrypt passcode for biometrics when enabling biometrics
-
-
> Update passcode for biometrics on enable

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionMultisendFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/LabeledArrayItem.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/LabeledNamedAddressItem.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/MultisendActionView.kt
- app/src/main/java/io/gnosis/safe/utils/ParamSerializer.kt
- app/src/main/res/layout/view_labeled_named_address_item.xml
- app/src/main/res/layout/view_multisend_action.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/test/java/io/gnosis/safe/ui/settings/owner/intro/OwnerGenerateViewModelTest.kt
- data/src/main/java/io/gnosis/data/models/transaction/TransactionDetails.kt
> Known addresses v3

- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/RepeatPasscodeFragment.kt
- app/src/test/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModelTest.kt
Handles #1519
- encryptPasscodeWithBiometricKey when enabling via dialog
> encryptPasscodeWithBiometricKey when enabling via dialog

- app/src/main/java/io/gnosis/safe/di/modules/RepositoryModule.kt
- data/build.gradle
Handles #1468 
- Removed unflavored BLOCKCHAIN_NET_URL from data/build.gradle
> Remove BLOCKCHAIN_NET_URL from data/build.gradle and fix imports

- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeCreatePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeRepeatPasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ConfigurePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/CreatePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/RepeatPasscodeFragment.kt
Handles #1508 
- Allow to show keyboard on all screens. 
> Activate onclicklistener to show keyboard.

- app/src/main/java/io/gnosis/safe/di/modules/ViewModelFactoryModule.kt
- app/src/main/java/io/gnosis/safe/di/modules/ViewModule.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionMultisendFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionViewModel.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionViewModelTest.kt
> Use local owner & safe names on multisend action screens

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionMultisendFragment.kt
> Use local safe & owner name data on multisend action list screen

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/AdvancedAppSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/AppSettingsFragment.kt
- app/src/main/res/layout/activity_start.xml
- app/src/main/res/layout/fragment_settings_app.xml
- app/src/main/res/layout/fragment_settings_app_advanced.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
> Add chain ribbon to safe overview screens 

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionFragment.kt
> Use known addresses from address info index in decoded arrays

- app/src/main/java/io/gnosis/safe/di/components/ApplicationComponent.kt
- app/src/main/java/io/gnosis/safe/di/modules/DatabaseModule.kt
- app/src/main/java/io/gnosis/safe/di/modules/RepositoryModule.kt
- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsFragment.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModelTest.kt
- data/build.gradle
- data/schemas/io.gnosis.data.db.HeimdallDatabase/4.json
- data/schemas/io.gnosis.data.db.HeimdallDatabase/5.json
- data/src/androidTest/java/io/gnosis/data/db/HeimdallDatabaseTest.kt
- data/src/main/java/io/gnosis/data/backend/GatewayApi.kt
- data/src/main/java/io/gnosis/data/db/HeimdallDatabase.kt
- data/src/main/java/io/gnosis/data/db/daos/ChainDao.kt
- data/src/main/java/io/gnosis/data/models/Chain.kt
- data/src/main/java/io/gnosis/data/models/ChainInfo.kt
- data/src/main/java/io/gnosis/data/models/Owner.kt
- data/src/main/java/io/gnosis/data/models/Safe.kt
- data/src/main/java/io/gnosis/data/models/SafeInfo.kt
- data/src/main/java/io/gnosis/data/repositories/ChainInfoRepository.kt
- data/src/main/java/io/gnosis/data/repositories/ChainRepository.kt
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
- data/src/main/java/io/gnosis/data/repositories/TokenRepository.kt
- data/src/main/java/io/gnosis/data/repositories/TransactionRepository.kt
- data/src/test/java/io/gnosis/data/repositories/ChainInfoRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/TokenRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/TransactionRepositoryTest.kt
- data/src/test/java/io/gnosis/data/utils/SafeTxHashTest.kt
Handles #1530 
- Introduce `ChainInfoRepository`
- Fetch from new endpoint (`v1/chains`) and parse JSON
- Modify all other calls to previous endpoints to have a default chaind of 4 (Rinkeby)
> Fetch network info and parse it

- app/build.gradle
- app/src/main/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionFragment.kt
> Release 2.18.0

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/safe/selection/SafeSelectionAdapter.kt
- app/src/main/java/io/gnosis/safe/ui/safe/selection/SafeSelectionViewData.kt
- app/src/main/java/io/gnosis/safe/ui/safe/selection/SafeSelectionViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/safe/share/ShareSafeDialog.kt
- app/src/test/java/io/gnosis/safe/ui/safe/SafeSelectionViewModelTest.kt
- data/build.gradle
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
> Add default chain data for flavors

- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/CollectibleViewData.kt
- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesViewHolderFactory.kt
- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/details/CollectiblesDetailsFragment.kt
- app/src/main/res/layout/fragment_collectibles_details.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/test/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesViewModelTest.kt
> Add chain ribbon to collectible details

- data/build.gradle
> Change client gateway url for staging_mainnet

- app/src/main/java/io/gnosis/safe/notifications/models/PushNotification.kt
- app/src/test/java/io/gnosis/safe/notifications/PushNotificationTest.kt
Handles #
- The backend already sends the chainId
> Parse chainId in push notifications

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/safe/selection/SafeSelectionViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionView.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/AdvancedTransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/CreationTransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionMultisendFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/res/layout/fragment_settings_app_advanced.xml
- app/src/main/res/layout/fragment_transaction_details.xml
- app/src/main/res/layout/fragment_transaction_details_action.xml
- app/src/main/res/layout/fragment_transaction_details_action_multisend.xml
- app/src/main/res/layout/fragment_transaction_details_advanced.xml
- app/src/main/res/layout/fragment_transaction_details_creation.xml
- app/src/main/res/layout/view_multisend_action.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
- data/src/main/java/io/gnosis/data/models/Safe.kt
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
> Add chain ribbon to tx details

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/ui/settings/chain/ChainSelectionFragment.kt
> Fix empty placeholder logic for chain list screen; add screen id

- data/src/main/java/io/gnosis/data/backend/GatewayApi.kt
Handles #1566
- Changes paths to be more RESTful as requested by backend
- **Do not merge before deployed on staging!**
> Move chainId

- app/src/main/java/io/gnosis/safe/notifications/NotificationManager.kt
- app/src/main/java/io/gnosis/safe/notifications/NotificationRepository.kt
- app/src/main/java/io/gnosis/safe/notifications/models/PushNotification.kt
- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/safe/share/ShareSafeDialog.kt
- app/src/main/java/io/gnosis/safe/ui/settings/chain/paging/ChainPagingSource.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsViewModel.kt
- app/src/main/res/layout/fragment_add_safe_name.xml
- app/src/main/res/layout/fragment_add_safe_owner.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/notifications/PushNotificationTest.kt
- app/src/test/java/io/gnosis/safe/ui/settings/SafeSettingsViewModelTest.kt
- app/src/test/resources/tx_details_transfer.json
- data/schemas/io.gnosis.data.db.HeimdallDatabase/5.json
- data/src/main/java/io/gnosis/data/adapters/MoshiBuilder.kt
- data/src/main/java/io/gnosis/data/adapters/TokenTypeAdapter.kt
- data/src/main/java/io/gnosis/data/backend/GatewayApi.kt
- data/src/main/java/io/gnosis/data/db/HeimdallDatabase.kt
- data/src/main/java/io/gnosis/data/db/daos/ChainDao.kt
- data/src/main/java/io/gnosis/data/models/Chain.kt
- data/src/main/java/io/gnosis/data/models/ChainInfo.kt
- data/src/main/java/io/gnosis/data/models/Safe.kt
- data/src/main/java/io/gnosis/data/models/transaction/TransferInfo.kt
- data/src/main/java/io/gnosis/data/repositories/ChainInfoRepository.kt
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
- data/src/main/java/io/gnosis/data/repositories/TokenRepository.kt
- data/src/test/java/io/gnosis/data/repositories/ChainInfoRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
- data/src/test/resources/load_balances_usd.json
- data/src/test/resources/tx_details_transfer.json
Handles #1304
Handles #1565
Handles #1578
- Remove obsolete shadow from add safe flow layouts
- Fix snackbar position in receiver dialog
- Adjust chain info parsing; parse & save native currency data
- Use chain data to select active safe
- Show chain name in notification title
- Use chain's native currency params to format transfer amount for native currency
- Adjust notification groups
- Adjust db schema & migration
> Adjust push notification handling & navigation

- data/src/androidTest/java/io/gnosis/data/db/HeimdallDatabaseTest.kt
- data/src/main/java/io/gnosis/data/db/HeimdallDatabase.kt
> Fix db migration

- app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt
- app/src/main/java/io/gnosis/safe/di/modules/RepositoryModule.kt
- app/src/test/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/dialogs/EnsInputViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/safe/SafeSelectionViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeNameViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
- buildsystem/versions.gradle
- data/build.gradle
- data/schemas/io.gnosis.data.db.HeimdallDatabase/5.json
- data/src/main/java/io/gnosis/data/db/HeimdallDatabase.kt
- data/src/main/java/io/gnosis/data/models/Chain.kt
- data/src/main/java/io/gnosis/data/models/ChainInfo.kt
- data/src/main/java/io/gnosis/data/models/Safe.kt
- data/src/main/java/io/gnosis/data/repositories/EnsRepository.kt
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
- data/src/test/java/io/gnosis/data/repositories/ChainInfoRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/EnsRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/UnstoppableRepositoryTest.kt
Handles #1557
- Save blockExplorerUrl and rpcUrl in chains table
- Use chain's rpcUrl to setup ethereum repo
> Add dynamic ENS support

- app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt
- app/src/main/java/io/gnosis/safe/notifications/NotificationManager.kt
- app/src/main/java/io/gnosis/safe/notifications/NotificationRepository.kt
- app/src/main/java/io/gnosis/safe/notifications/NotificationServiceApi.kt
- app/src/main/java/io/gnosis/safe/notifications/firebase/HeimdallFirebaseService.kt
- app/src/main/java/io/gnosis/safe/notifications/models/Registration.kt
- app/src/main/java/io/gnosis/safe/ui/splash/SplashViewModel.kt
- app/src/main/java/io/gnosis/safe/workers/HeimdallWorkerFactory.kt
- app/src/main/java/io/gnosis/safe/workers/NotificationsRegistrationWorker.kt
- app/src/main/java/io/gnosis/safe/workers/WorkRepository.kt
- app/src/test/java/io/gnosis/safe/notifications/RegistrationTest.kt
- app/src/test/java/io/gnosis/safe/ui/splash/SplashViewModelTest.kt
Handles #1563
- Adjust registration endpoint
- Adjust registration payload
- Add worker for registration work
> Push notification registration with multiple network support

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionMultisendFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/utils/BalanceFormatter.kt
- app/src/main/java/io/gnosis/safe/utils/TxUtils.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/details/viewdata/TransactionDetailsViewDataTest.kt
- app/src/test/java/io/gnosis/safe/utils/TxUtilsKtTest.kt
- data/src/main/java/io/gnosis/data/adapters/MoshiBuilder.kt
- data/src/main/java/io/gnosis/data/models/transaction/TransferInfo.kt
- data/src/main/java/io/gnosis/data/repositories/TokenRepository.kt
- data/src/main/java/io/gnosis/data/utils/SafeTxHash.kt
- data/src/test/java/io/gnosis/data/repositories/TokenRepositoryTest.kt
- data/src/test/java/io/gnosis/data/repositories/TransactionRepositoryTest.kt
> Handle native currencies of the chain

- app/src/main/res/values/strings.xml
> Correct toolbar titles for generate owner key flow

- app/src/main/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/utils/BlockExplorer.kt
- app/src/main/res/layout/fragment_settings_safe_advanced.xml
- app/src/main/res/values/static_strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/settings/SafeSettingsViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsViewModelTest.kt
- data/src/main/java/io/gnosis/data/models/SafeInfo.kt
- data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
Handles #1491
- Add guard section to advanced safe settings
- Show guard for contracts >= 1.3.0
> Add guard section to advanced safe settings

- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/details/CollectiblesDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeOwnerFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/share/ShareSafeDialog.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/details/OwnerDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/view/AddressItem.kt
- app/src/main/java/io/gnosis/safe/ui/settings/view/MasterCopyItem.kt
- app/src/main/java/io/gnosis/safe/ui/settings/view/NamedAddressItem.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/CreationTransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/LabeledAddressItem.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/LabeledArrayItem.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/LabeledNamedAddressItem.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxConfirmationsView.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxSettingsActionView.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxTransferActionView.kt
- app/src/main/java/io/gnosis/safe/utils/BlockExplorer.kt
- app/src/main/res/layout/fragment_owner_details.xml
- app/src/main/res/values/static_strings.xml
- app/src/test/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsViewModelTest.kt
Handles #1577
- Use block explorer utility for opening addresses
> Use blockEsplorerUrl from chain when opening addresses

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
- data/src/main/java/io/gnosis/data/models/transaction/Transaction.kt
Handles #
- queue list failed because of typ change
> Use AddressInfo in missingSigners

- app/src/main/res/layout/fragment_transaction_details.xml
- app/src/main/res/layout/fragment_transaction_details_creation.xml
- app/src/main/res/values/strings.xml
- data/src/main/java/io/gnosis/data/models/ChainInfo.kt
> View on etherscan -> view on block explorer string adjustment

- app/src/main/res/layout/view_tx_status.xml
> Fix outgoing/incoming icons too big on tx details page

- app/src/main/java/io/gnosis/safe/ui/safe/selection/SafeSelectionViewModel.kt
> Remove network ribbon from the switch safe list when the last safe is removed

- app/src/main/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionFragment.kt
> Show proper error message if tx rejection fails due to connectivity

- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerEnterNameFragment.kt
- data/src/main/java/io/gnosis/data/security/HeimdallEncryptionManager.kt
> Fix biometric login 

- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt
> Fix address field is cleaned up after app is callled from backgroud

- data/src/main/java/io/gnosis/data/models/transaction/TransactionDetails.kt
> Fix tx details parsing

- app/src/main/java/io/gnosis/safe/ui/settings/app/GetInTouchFragment.kt
- app/src/main/res/values/strings.xml
> Add chain info to the feedback email body

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/utils/TxUtils.kt
- app/src/test/java/io/gnosis/safe/utils/TxUtilsKtTest.kt
> Load native currency icon for native transfers using chain data

- app/src/main/res/layout/item_tx_contract_interaction.xml
- app/src/main/res/layout/item_tx_queued_contract_interaction.xml
- app/src/main/res/layout/view_tx_status.xml
- buildsystem/versions.gradle
> Fix UI issues with App icon (#1330)

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/helpers/AddressInputHelper.kt
- app/src/main/java/io/gnosis/safe/ui/dialogs/UnstoppableInputDialog.kt
- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeNameViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsViewModel.kt
- app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeNameViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/settings/SafeSettingsViewModelTest.kt
> Track chainId when adding/removing safe and on scanner screen; Fix UD screenId

- app/build.gradle
- app/src/main/java/io/gnosis/safe/ui/settings/owner/details/OwnerDetailsFragment.kt
> Prevent double clicking on remove owner button

- app/src/main/java/io/gnosis/safe/ui/settings/owner/ledger/LedgerController.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/ledger/LedgerOwnerSelectionViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/ledger/LedgerSignDialog.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/ledger/LedgerSignViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/ledger/LedgerTabsFragment.kt
- clear old signature action in LedgerSignViewModel
- continuation stacks
> Bugfix for old signature residue from previous signing in LedgerSignDialog

- app/src/main/res/values/strings.xml
Handles #1694
Scan | Load Addresses
----- | ----------
> Tell user to enable location services if no ledger was found

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
> Ask for PIN if enabled when app opened from push

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/EnterPasscodeFragment.kt
> Fix unlocking with fingerprint after putting app to background

- app/src/main/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
> Fix disabled passcode not allowing to confirm transactions

- app/build.gradle
> Release 3.2.0

- app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
- app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
> Fix launcher icons

- app/build.gradle
- app/src/main/res/values/static_strings.xml
- ci/upload_app_distribution.sh
- ci/upload_to_github.sh
> Release 3.3.0

- app/build.gradle
- ci/upload_to_github.sh
- qrscanner/src/main/java/io/gnosis/safe/qrscanner/QRCodeScanActivity.kt
> Release 3.3.1

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
Handles #1798
- Ensure what's new is shown after pin input
> Adjust what's new showing conditions

- app/src/main/java/io/gnosis/safe/ui/assets/AssetsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/assets/AssetsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsViewModel.kt
- app/src/main/res/layout/fragment_assets.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/assets/coins/CoinsViewModelTest.kt
Handles #1780
- Add header for total balance
- Remove total balance from coins list
- Show share safe dialog when receive button is clicked
> [Send Funds] Total balance header

- data/build.gradle
Handles #1810 
- New URLs for staging
- Untested
> Migrate to new CGW URL

- app/build.gradle
- app/src/main/java/io/gnosis/safe/ui/settings/app/AdvancedAppSettingsFragment.kt
- data/build.gradle
> Remove tx service url

- app/src/main/res/layout/fragment_add_safe_owner.xml
> Make label wider to fit content in one line

- app/build.gradle
- data/build.gradle
Handles #1824
- Change URL for CGW
- Disable SSL-Pinning for gnosis.io
> New CGW for prod (on release branch)

- app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/send_funds/SendAssetFragment.kt
> Handle scanner results for send asset screen

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/di/components/ViewComponent.kt
- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/assets/AssetsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/base/SafeOverviewBase.kt
- app/src/main/java/io/gnosis/safe/ui/safe/send_funds/AddOwnerFirstFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/CreatePasscodeFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/details/OwnerDetailsViewModel.kt
- app/src/main/res/layout/fragment_add_owner_first.xml
- app/src/main/res/layout/fragment_success.xml
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/settings/owner/details/OwnerDetailsViewModelTest.kt
- data/src/main/java/io/gnosis/data/models/Safe.kt
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
Handles #1839
- Add owner key first screen
> [Send funds] Add owner key first

- app/src/main/java/io/gnosis/safe/helpers/AddressInputHelper.kt
- app/src/main/java/io/gnosis/safe/ui/safe/send_funds/SendAssetFragment.kt
- app/src/main/res/layout/fragment_send_asset.xml
Handles #1840
Handles #1849
- Add review toolbar button to send asset screen
- Fix scanning MM qr codes
> Scan MM qr codes

- app/src/main/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsViewModel.kt
- app/src/main/res/layout/fragment_settings_safe_advanced.xml
- app/src/main/res/navigation/main_nav.xml
> Network ribbon for advanced safe settings screen

- app/src/main/java/io/gnosis/safe/ui/safe/send_funds/SendAssetReviewFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/send_funds/SendAssetReviewViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/SigningOwnerSelectionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
- app/src/main/res/navigation/main_nav.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/settings/owner/list/OwnerListViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionViewModelTest.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModelTest.kt
- data/build.gradle
- data/src/main/java/io/gnosis/data/repositories/TransactionRepository.kt
Handles #1838
- Create transfer transaction
- Calculate safeTxHash and sign it with selected owner
- Encode erc20 transfer data
- Propose transfer transaction
- Connect elements of the send funds flow
> [Send funds] Initiate transfer

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
- app/src/main/java/io/gnosis/safe/ui/assets/AssetsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/safe/send_funds/AddOwnerFirstFragment.kt
> [Send funds] Tracking

- app/src/main/java/io/gnosis/safe/notifications/NotificationManager.kt
> Fix pending intent crash

- app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
> Do not show whats new for current version

- app/src/main/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesFragment.kt
> Prevent list from reloading when coming back from details

- app/src/main/java/io/gnosis/safe/notifications/NotificationManager.kt
> Revert changes to pending intent config

- app/src/main/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionFragment.kt
> Reenable reject button after back navigation from signer selection

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- Update bug report template
- Add bug report issue form
- Add contact links
> Bug issue form

- app/build.gradle
- app/proguard-rules.pro
- app/src/main/java/io/gnosis/safe/ui/assets/AssetsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsFragment.kt
- app/src/main/res/layout/fragment_owner_export.xml
Handles #1879
Handles #1884
Handles #1885
> Release fixes

- app/src/main/java/io/gnosis/safe/ui/settings/app/GetInTouchFragment.kt
- app/src/main/res/values/static_strings.xml
> Change URL of discord invite link

- app/build.gradle
> Release 3.6.2

- app/src/main/res/values/static_strings.xml
> Update terms and policy links

- app/build.gradle
> Release 3.6.3

- app/src/main/AndroidManifest.xml
- app/src/main/res/values/static_strings.xml
- buildsystem/versions.gradle
Handles #1906
- Upgrade to Intercom 14.0.0
- Fix broken dependencies
- Set region
> Intercom upgrade and workspace migration (us -> eu)

- app/build.gradle
> Release 3.6.4

- .github/workflows/cla.yml
> CLA Workflow

- app/build.gradle
> Release 3.6.5

- app/src/main/java/io/gnosis/safe/ui/safe/share/ShareSafeDialog.kt
- app/src/main/java/io/gnosis/safe/ui/settings/app/SettingsHandler.kt
- app/src/main/res/layout/dialog_share_safe.xml
- app/src/main/res/layout/fragment_settings_app_passcode.xml
- app/src/main/res/layout/view_settings_item.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Handles #1917
- Extend safe info screen with chain prefix setting
- Actual setting application will be covered by #1918
> Add QR with chain prefix setting

- app/build.gradle
> Release 3.7.0

- app/build.gradle
- app/src/main/java/io/gnosis/safe/ui/settings/owner/keystone/KeystoneRequestSignatureFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/keystone/KeystoneSignViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/view/AddressItem.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionViewModel.kt
- data/src/main/java/io/gnosis/data/repositories/CredentialsRepository.kt
> Release 3.8.0

- app/src/main/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- data/src/main/java/io/gnosis/data/models/transaction/TransactionDetails.kt
> Support nullable rejectors list

- app/build.gradle
- app/src/main/java/io/gnosis/safe/notifications/NotificationRepository.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/keystone/KeystoneRequestSignatureFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/keystone/KeystoneSignViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionView.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/SigningOwnerSelectionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/viewdata/TransactionDetailsViewData.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewViewModel.kt
- app/src/main/res/navigation/main_nav.xml
- data/build.gradle
- data/src/main/java/io/gnosis/data/adapters/ParcelizeUtils.kt
- data/src/main/java/io/gnosis/data/models/AddressInfo.kt
- data/src/main/java/io/gnosis/data/models/transaction/DataDecoded.kt
- data/src/main/java/io/gnosis/data/models/transaction/TransactionDetails.kt
- data/src/main/java/io/gnosis/data/models/transaction/TransferInfo.kt
- data/src/main/java/io/gnosis/data/utils/SignatureUtils.kt
Handles #1960
- Ask for password when required before execution
- Adjust execution flow for keystone keys
- Fix crash when trying to use hd keys for push registration
> Adjust execution flow for keystone keys

- app/src/main/java/io/gnosis/safe/ui/settings/owner/keystone/KeystoneSignViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxEditFeeViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewViewModel.kt
- app/src/main/java/io/gnosis/safe/utils/StringUtils.kt
- app/src/main/res/layout/fragment_tx_edit_fee_legacy.xml
- buildsystem/versions.gradle
- data/src/main/java/io/gnosis/data/backend/rpc/RpcClient.kt
- data/src/main/java/io/gnosis/data/backend/rpc/models/EstimationParams.kt
- data/src/main/java/io/gnosis/data/db/TypeConverters.kt
- data/src/main/java/io/gnosis/data/repositories/EnsRepository.kt
- data/src/test/java/io/gnosis/data/repositories/EnsRepositoryTest.kt
Handles #1964
- Execute transactions on chains without EIP-1559 support
- Adjust ledger signing for execution
not covered in this pr: monitoring of the transaction submitted for execution
> Legacy transaction execution

- app/src/main/java/io/gnosis/safe/Tracker.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/SigningOwnerSelectionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewViewModel.kt
Handles #1962
- Add tracking for estimated fee fields
- Add tracking for execution key changed
- Refactor header ui setup
> Adjust tracking; improve readability of the review tx ui setup

- buildsystem/versions.gradle
Use latest release of the svalinn lib
> Update svalinn lib

- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewViewModel.kt
- app/src/main/res/values/strings.xml
- buildsystem/versions.gradle
- data/src/main/java/io/gnosis/data/backend/rpc/RpcClient.kt
Handles #1970
- Error handling
- Fix rlp encoding for eip-1559
> Show snackbar regarding tx estimation and submission errors

- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewViewModel.kt
- data/src/main/java/io/gnosis/data/backend/rpc/RpcClient.kt
Handles #1980
Handles #1981
- Fix estimation
> Fix estimation; add get tx receipt call

- app/build.gradle
Handles #1991
- update version
> Update version for release

- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewViewModel.kt
- app/src/test/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModelTest.kt
Handles #1997
- Disable selction of ledger key as default
- remove ledger keys from eligible key list 
- disable execution button if no other owner keys are available
> Disable ledger keys for execution

- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
> GH-1996 - 1.3.0 is the oldest up to date version

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
Handles: #2005
- Ignore check if submittedAt is null
> Missing incoming transfers

- app/src/main/java/io/gnosis/safe/ui/safe/send_funds/SendAssetReviewViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewViewModel.kt
> Add clarifying comments and TODOs

- app/build.gradle
- app/src/main/java/io/gnosis/safe/ui/safe/send_funds/SendAssetReviewViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxConfirmationsView.kt
- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModelTest.kt
- data/build.gradle
- data/src/main/java/io/gnosis/data/backend/GatewayApi.kt
- data/src/main/java/io/gnosis/data/models/transaction/TransactionDetails.kt
- data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
Handles merging the changes made for the release  back to master
> Release 3.9.0

- app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt
Handles #2005
- Fix incoming transfers display
> Fix incoming transfers display

- app/src/main/java/io/gnosis/safe/ui/settings/owner/intro/OwnerInfoKeystoneFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/keystone/KeystoneOwnerPagingProvider.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/keystone/KeystoneOwnerPagingSource.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/keystone/KeystoneOwnerSelectionFragment.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/keystone/KeystoneOwnerSelectionViewModel.kt
- app/src/main/java/io/gnosis/safe/ui/settings/owner/keystone/KeystoneSignViewModel.kt
- app/src/main/java/io/gnosis/safe/utils/PublicKeyDerivator.kt
- app/src/main/res/navigation/main_nav.xml
- buildsystem/versions.gradle
- Updates to the project dependencies
> Fixing the project build

- data/src/main/java/io/gnosis/data/adapters/ParamAdapter.kt
Handles #2023
- Fixed data decoding of parameters
> Fixed failing decoding data

- app/build.gradle
- ci/upload_to_github.sh
Handles #2027
- Updating app version
> Update app version

- app/src/main/java/io/gnosis/safe/ui/settings/owner/keystone/KeystoneOwnerSelectionFragment.kt
> Attempt at fixing null pointer exception

- app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
- data/build.gradle
Handles #2029
- Update label in the header
> Update details header

- data/src/main/java/io/gnosis/data/utils/SafeTxHash.kt
Handles #2036 
- update receiver address
> GH-2036 changed the receiver address

- app/build.gradle
Handles #2035
- Update version number
> GH-2035 update version number

- app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewFragment.kt
- app/src/main/res/layout/tx_review_settings_change.xml
Handles #2040
- Added tx type to the review screen
> GH-2040 added tx type to the review screen

- build.gradle
- buildsystem/android_library.gradle
Handles #2051
- Updated the target sdk version to 34
> GH-2051 updated sdk target version
