app/src/main/java/pm/gnosis/heimdall/ui/base/BaseActivity.kt
- Prevent screens from appearing in screenshots or from being viewed on non-secure displays. 
=> WA-48: Secure Screens

app/src/main/java/pm/gnosis/heimdall/ui/authenticate/AuthenticateActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/authenticate/AuthenticateViewModel.kt, app/src/main/java/pm/gnosis/heimdall/ui/transactions/BaseTransactionActivity.kt, app/src/main/java/pm/gnosis/heimdall/utils/AppUtils.kt, app/src/test/java/pm/gnosis/heimdall/ui/authenticate/AuthenticateViewModelTest.kt
Fixed authenticate screen
- Use correct layout for error snackbar
- Enable scanning of any transaction
- Fixed handling of returned results from scanner
=> Fixed authenticate screen

app/src/main/java/pm/gnosis/heimdall/ui/safe/overview/SafeOverviewViewModel.kt, app/src/test/java/pm/gnosis/heimdall/ui/safe/SafeOverviewViewModelTest.kt
- Load safe info from network before getting it from the view model cache
=> WA-101: Load safe info from network before getting it from the view model cache

app/src/main/java/pm/gnosis/heimdall/ui/settings/SettingsActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/settings/security/SecuritySettingsActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/settings/security/SecuritySettingsContract.kt, app/src/main/java/pm/gnosis/heimdall/ui/settings/security/SecuritySettingsViewModel.kt, app/src/main/res/layout/layout_security_settings.xml, app/src/test/java/pm/gnosis/heimdall/ui/settings/security/SecuritySettingsViewModelTest.kt, buildsystem/dependencies.gradle
- Show Security Settings on every version
- Hide the Fingerprint section in Security Settings 
=> WA-111: Fix security settings visibility on pre Android 6

app/src/main/java/pm/gnosis/heimdall/ui/base/SecuredBaseActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/onboarding/account/create/GenerateMnemonicActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/onboarding/account/restore/RestoreAccountActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/onboarding/password/PasswordSetupActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/security/unlock/UnlockActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/settings/security/revealmnemonic/RevealMnemonicActivity.kt, app/src/main/java/pm/gnosis/heimdall/utils/ViewUtils.kt, app/src/main/res/values/strings.xml, gradle.properties
Closes WA-112.
- Try to warn the user about obscured windows (click jacking)
- Disable accessibility services for critical input fields
=> WA-112: Added security flags

app/build.gradle, app/schemas/pm.gnosis.heimdall.data.db.ApplicationDb/1.json, app/src/main/java/pm/gnosis/heimdall/common/di/modules/ApplicationModule.kt, app/src/main/java/pm/gnosis/heimdall/data/db/ApplicationDb.kt, app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultAddressBookRepository.kt, app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultGnosisSafeRepository.kt, app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTokenRepository.kt, app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/GnosisSafeTransactionRepository.kt, app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/SimpleTransactionDetailsRepository.kt, app/src/main/java/pm/gnosis/heimdall/ui/dialogs/share/RequestSignatureDialog.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/add/DeployNewSafeFragment.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/details/SafeDetailsActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/overview/SafesOverviewActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/transactions/SignTransactionActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/transactions/SubmitTransactionActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/transactions/ViewTransactionContract.kt, app/src/main/java/pm/gnosis/heimdall/ui/transactions/ViewTransactionViewModel.kt, app/src/main/java/pm/gnosis/heimdall/ui/transactions/details/safe/CreateAddOwnerDetailsFragment.kt, app/src/main/res/layout/dialog_request_signature.xml, app/src/main/res/layout/layout_create_add_safe_owner.xml, app/src/main/res/layout/layout_pending_safe_item.xml, app/src/main/res/layout/layout_submit_transaction.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTokenRepositoryTest.kt, app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/GnosisSafeTransactionRepositoryTest.kt, app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/SimpleTransactionDetailsRepositoryTest.kt, app/src/test/java/pm/gnosis/heimdall/ui/transactions/ViewTransactionViewModelTest.kt, heimdall-common/src/main/java/pm/gnosis/heimdall/common/utils/ObservableUtils.kt
Closes WA-133 and WA-137.
- Move request signature via push button from dialog to activity
- Fab on safe details opens scan transaction screen
- Fix create add owner transaction screen
- Renamed application database classes/files (this needs a reset of the app)
=> WA-133: Adjust request signature flow

README.md
Closes #155 .
- There was no build status indicator in the README. This will add a travis build status badge to it.
=> #155: Add travis badge to readme

ci/notify_slack.sh, ci/prepare_env.sh
- Buildscript included unnecessary `echo` statements and a hard coded slack url. These have been removed
=> Remove unnecessary information from ci scripts

app/src/main/java/pm/gnosis/heimdall/helpers/GoogleSmartLockHelper.kt, app/src/main/java/pm/gnosis/heimdall/ui/onboarding/account/AccountSetupActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/onboarding/account/AccountSetupContract.kt, app/src/main/java/pm/gnosis/heimdall/ui/onboarding/account/AccountSetupViewModel.kt, app/src/main/java/pm/gnosis/heimdall/utils/AppUtils.kt
- The flow for restoring the account via Google Smart Lock assumed that once it was stored it was immediately accessible (which is not the case). The new flow doesn't try to retrieve the account once it is stored.
=> Fix issue with Google Smart Lock

app/src/main/java/pm/gnosis/heimdall/ui/onboarding/password/PasswordConfirmActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/onboarding/password/PasswordSetupActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/add/DeployNewSafeFragment.kt
• WA-290: An error message should be shown to the user when something went wrong when clicking the deploy with external wallet button
• WA-291: Disable external wallet button while deploy is in progress
• WA-292: Enable password screen progression with softkeyboard
=> WA-285: Fix issues for internal test

README.md, docs/CONTRIBUTING.md
- Repo was called heimdall-android before. Now it is called safe-android
=> Adjusted docs to new repo name

app/src/main/java/pm/gnosis/heimdall/data/repositories/TokenRepository.kt, app/src/main/java/pm/gnosis/heimdall/data/repositories/TransactionInfoRepository.kt, app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTokenRepository.kt, app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTransactionInfoRepository.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsViewModel.kt, app/src/main/java/pm/gnosis/heimdall/ui/tokens/add/AddTokenActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/tokens/add/AddTokenContract.kt, app/src/main/java/pm/gnosis/heimdall/ui/tokens/add/AddTokenViewModel.kt, app/src/main/java/pm/gnosis/heimdall/ui/transactions/create/CreateAssetTransferViewModel.kt, app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/confirm/ConfirmTransactionViewModel.kt, app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/status/TransactionStatusViewModel.kt, app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/viewholders/AssetTransferViewHolder.kt, app/src/main/res/values/strings.xml, app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTokenRepositoryTest.kt, app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultTransactionInfoRepositoryTest.kt, app/src/test/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsViewModelTest.kt, app/src/test/java/pm/gnosis/heimdall/ui/tokens/add/AddTokenViewModelTest.kt, app/src/test/java/pm/gnosis/heimdall/ui/transactions/create/CreateAssetTransferViewModelTest.kt, app/src/test/java/pm/gnosis/heimdall/ui/transactions/view/confirm/ConfirmTransactionViewModelTest.kt, app/src/test/java/pm/gnosis/heimdall/ui/transactions/view/status/TransactionStatusViewModelTest.kt, app/src/test/java/pm/gnosis/heimdall/ui/transactions/view/viewholders/AssetTransferViewHolderTest.kt
Closes WA-420.
- Restrict transactions that change threshold or change master copy
- Refactor `loadToken` (local) and `loadTokenInfo` (network) into one method `loadToken` which first does a local lookup and if nothing is found a network lookup
=> WA-420: Adjust restricted transactions

app/src/main/java/pm/gnosis/heimdall/data/repositories/models/Safe.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/main/SafeMainActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/tokens/receive/ReceiveTokenActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/tokens/receive/ReceiveTokenViewModel.kt, app/src/main/res/color/primary_button_white_text.xml, app/src/main/res/layout/layout_receive_token.xml, app/src/main/res/layout/layout_safe_transactions.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Closes WA-422.
- Display default title if safe has no name
- Adjust empty transactions screen
- Show loading spinner for qr code generation on Receive screen
- Adjust disabled state of primary button (text color)
=> WA-422: Design adjustments

app/src/main/java/pm/gnosis/heimdall/ui/safe/create/ConfirmSafeRecoveryPhraseAdapter.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/create/CreateSafeIntroActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/details/SafeDetailsFragment.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/main/SafeMainActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/mnemonic/InputRecoveryPhraseActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/address/CheckSafeActivity.kt, app/src/main/java/pm/gnosis/heimdall/utils/ViewUtils.kt, app/src/main/res/layout/layout_check_safe.xml, app/src/main/res/layout/layout_confirm_safe_recovery_phrase_item.xml, app/src/main/res/layout/layout_create_safe_intro.xml, app/src/main/res/layout/layout_input_recovery_phrase.xml, app/src/main/res/layout/layout_safe_details.xml, app/src/main/res/layout/layout_safe_main.xml
Closes WA-487.
- Add new extension function to set (vector) drawable resources in a backwards compatibility fashion.
- Replace all direct usages of vector resources in TextViews with the new extension function.
=> WA-487: Fix crashes on API19 due to the use of vector resources

app/src/main/java/pm/gnosis/heimdall/ui/safe/main/SafeMainActivity.kt
- Set Settings vector drawable in navigation drawer
=> Set Settings vector drawable in navigation drawer

app/src/main/java/pm/gnosis/heimdall/di/modules/ApplicationModule.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/submit/RecoveringSafeViewModel.kt, app/src/test/java/pm/gnosis/heimdall/ui/safe/recover/submit/RecoveringSafeViewModelTest.kt, buildsystem/dependencies.gradle
Closes #63.
- Enable password stretching and hardware encryption (Svalinn 0.6.0)
- Don't request ExecuteInformation for stored recovery (build from stored information)
=> Closes #63: Enable password stretching and hardware encryption

app/src/main/java/pm/gnosis/heimdall/ui/splash/SplashActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/splash/SplashContract.kt, app/src/main/java/pm/gnosis/heimdall/ui/splash/SplashViewModel.kt, app/src/test/java/pm/gnosis/heimdall/ui/splash/SplashViewModelTest.kt
Closes #228.
- If app is locked on splash start unlock screen to prevent "white flash"
=> Closes #228: Prevent flashing on fresh start

.travis.yml, build.gradle, buildsystem/dependencies.gradle
- Kotlin (1.2.61 -> 1.2.71)
- Android Tools Gradle Plugin (3.1.4 -> 3.2.0)
- Google Services Gradle Plugin (3.3.0 -> 4.1.0)
- Build Tools (28.0.2 -> 28.0.3)
=> Update dependencies. Using new Android Tools Gradle Plugin.

app/src/main/java/pm/gnosis/heimdall/ui/safe/main/SafeMainActivity.kt
Closes #252
- Hide "Replace recovery phrase" and "Replace browser extension" if the safe is not created yet
=> Do not show recovery options when Safe creation is pending

app/src/main/java/pm/gnosis/heimdall/data/repositories/PushServiceRepository.kt, app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepository.kt, app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/helpers/SubmitTransactionHelper.kt, app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepositoryTest.kt, app/src/test/java/pm/gnosis/heimdall/ui/transactions/view/helpers/DefaultSubmitTransactionHelperTest.kt
- Set correct gasToken in requestConfirmation push message
=> Send gas token in push

.buildkite/pipeline.yml, buildsystem/dependencies.gradle, ci/google-services.json.sample, ci/transform_with_R8.sh, gradle.properties
- Switch to R8
- Update Moshi
- Buildkite now requires R8 (switching to Proguard will make the build fail)
=> Switch to R8

app/proguard-rules.pro
- Added proguard rules to keep JsonQualifier annotations
- see https://github.com/square/moshi/issues/799
=> Added additional rules to keep JsonQualifier annotations

app/src/main/java/pm/gnosis/heimdall/data/remote/PushServiceApi.kt, app/src/main/java/pm/gnosis/heimdall/data/remote/models/push/PushServiceAuth.kt, app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepository.kt, app/src/main/java/pm/gnosis/heimdall/ui/security/unlock/UnlockViewModel.kt, app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/DefaultPushServiceRepositoryTest.kt
Closes #348.
- Use v2 of auth endpoint
=> Use new auth endpoint

app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/helpers/SubmitTransactionHelper.kt, app/src/test/java/pm/gnosis/heimdall/ui/transactions/view/helpers/DefaultSubmitTransactionHelperTest.kt
- Instead of casting to array and converting to map, we map the array. This is possible since we know the expected datatypes
=> Fix casting from array to map

app/build.gradle, app/src/main/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsAdapter.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsContract.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsViewModel.kt, app/src/main/java/pm/gnosis/heimdall/ui/transactions/TransactionSubmissionConfirmationDialog.kt, app/src/main/java/pm/gnosis/heimdall/utils/DateTimeUtils.kt, app/src/main/res/layout/include_transaction_submit_info.xml, app/src/main/res/layout/layout_create_asset_transfer.xml, app/src/test/java/pm/gnosis/heimdall/ui/safe/details/transactions/AdapterEntryHeaders.kt, app/src/test/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsAdapterHeaderViewHolderTest.kt, app/src/test/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsAdapterTransactionViewHolderTest.kt, app/src/test/java/pm/gnosis/heimdall/ui/safe/details/transactions/SafeTransactionsViewModelTest.kt, app/src/test/java/pm/gnosis/heimdall/ui/safe/details/transactions/test/AdapterEntryHeaders.kt, buildsystem/dependencies.gradle
Closes #370: Adjust transaction list headers
- the header between entries correspond to the data (no grouping of multiple dates)
=> Adjust transaction list headers (#370)

app/src/main/java/pm/gnosis/heimdall/HeimdallApplication.kt, buildsystem/dependencies.gradle
Closes #225: Enable RxAndroid's new async api
- enable async api
- see https://app.zenhub.com/workspaces/gnosis-safe-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/225 for profiling info
=> Enable RxAndroid's new async api (#225)

app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/SafeAccountRepository.kt, app/src/test/java/pm/gnosis/heimdall/data/repositories/impls/SafeAccountRepositoryTest.kt, app/src/test/java/pm/gnosis/heimdall/helpers/SvalinnCryptoHelperTest.kt
Closes #396.
- Added crypto helper tests
- Added tests for Safe account repository
=> Closes #396: Add tests for CryptoHelper and SafeAccountRepository

ci/upload_crashlytic_versions.sh
In some refactoring a copy paste error happened and the release version is not uploaded to crashlytics anymore. This PR fixes that
=> Fix crashlytics upload script

app/src/main/java/pm/gnosis/heimdall/ui/safe/main/SafeMainActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingStartActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/recoveryphrase/SetupNewRecoveryPhraseIntroActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/safe/RecoverSafe2FAActivity.kt, app/src/main/java/pm/gnosis/heimdall/ui/two_factor/authenticator/PairingAuthenticatorActivity.kt, app/src/main/res/layout/layout_recovery_phrase_intro.xml, app/src/main/res/layout/screen_pairing_review.xml, app/src/main/res/menu/safe_details_menu.xml
=> Closes #500: Release 1.9.0 issues

app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/safe/submit/RecoveringSafeContract.kt, app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/safe/submit/RecoveringSafeViewModel.kt
Closes #332 .
Currently we react and display following errors during mnemonic input
- SafeInfoError
- InvalidMnemonic => invalid recovery phrase
- WrongMnemonic => wrong recovery phrase for safe
- RecoverDataError
- NoRecoveryNecessary
Safe address is being checked on the address input screen which comes at the begining of the flow. Thus errors like wrong safe address or address that cannot be found on network will be filtered during this step.
Hence user should be properly informed about most of the errors.
- Add specific exception in case transaction fails during recovery
=> Closes #332: Add specific exception in case of transaction failure during recovery

app/src/main/res/values/strings.xml
Closes #479.
- Fix misspelled "create password" hint 
=> Closes #479: Correct typo

.travis.yml, build.gradle
Closes #475: Cannot create safe with keycard on MotoG.
- Update compileSdk & targetSdk versions
=> Update compileSdk & targetSdk versions

ci/upload_crashlytics_versions.sh, ci/upload_to_github.sh
- workaround for setting APP_VERSION when build triggered from tag
- git describe --tags --always not seeing the recent tag
=> Use tag name from buildkite env variable for app version name

README.md, docs/INTERNAL_BUILD.md, docs/RELEASE.md
Closes #583 .
- Update README.md instructions on Infura API-Key now called project id
- Add instruction on `internal` builds
=> Closes #583 internal build documentation

app/build.gradle, buildsystem/android_library.gradle, data/build.gradle
For the internal build we do not want to use the production services. We want to be able to use new features, when they are deployed to staging.
Closes # .
- Move config of TRANSACTION_SERVICE_URL & RELAY_SERVICE_URL to data module
- Align debug/internal/rinkeby/release build types wit respective services
- 
=> Transaction- and Relay-Service are now configured in data module

app/src/main/java/io/gnosis/safe/Tracker.kt, app/src/main/java/io/gnosis/safe/di/components/ApplicationComponent.kt, app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt, app/src/main/java/io/gnosis/safe/helpers/AddressInputHelper.kt, app/src/main/java/io/gnosis/safe/ui/StartActivity.kt, app/src/main/java/io/gnosis/safe/ui/base/BaseActivity.kt, app/src/main/java/io/gnosis/safe/ui/base/BaseBottomSheetDialogFragment.kt, app/src/main/java/io/gnosis/safe/ui/base/BaseFragment.kt, app/src/main/java/io/gnosis/safe/ui/base/BaseViewBindingFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/SafeOverviewBase.kt, app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeNameFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/balances/SafeBalancesFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/balances/coins/CoinsFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/balances/coins/CoinsViewModel.kt, app/src/main/java/io/gnosis/safe/ui/safe/balances/collectibles/CollectiblesFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/empty/NoSafeFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/selection/SafeSelectionDialog.kt, app/src/main/java/io/gnosis/safe/ui/safe/settings/SettingsFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/settings/app/AdvancedAppSettingsFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/settings/app/AppSettingsFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/settings/app/GetInTouchFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/settings/safe/SafeSettingsFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/terms/TermsBottomSheetDialog.kt, app/src/main/java/io/gnosis/safe/ui/splash/SplashActivity.kt, app/src/main/java/io/gnosis/safe/ui/transaction/TransactionsFragment.kt
Closes #599 
- Manually track screens with firebase analytics
- Split BaseFragment into BaseFragment and BaseViewBindingFragment
- Use BaseFragment to track screen id for screen fragments
- Use BaseBottomSheetDialogFragment to track screen id of bottom sheet dialogs
- Use BaseActivity to track screen id for screens represented by activities outside of the main nav graph
=> Track screen names

app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt, app/src/main/res/color/text_button_color.xml, app/src/main/res/drawable/ic_baseline_arrow_back_24.xml, app/src/main/res/drawable/ic_link_green_24dp.xml, app/src/main/res/layout/fragment_add_safe.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
- "NEXT" button is disabled upon entering the screen
- Added color state list for text buttons and made them all caps
- Adjusted font styles and margins to match that of the designs
| Before | After |
|-------|-------|
|![image](https://user-images.githubusercontent.com/246473/84641801-e037d080-aefb-11ea-86a4-fedb6c16c285.png)|![image](https://user-images.githubusercontent.com/246473/84641789-dada8600-aefb-11ea-9eb3-5bc57b878c91.png)|
=> Enter safe screen design compliant

app/src/main/java/io/gnosis/safe/ui/safe/settings/app/AdvancedAppSettingsFragment.kt
Reference https://github.com/gnosis/safe-android/issues/657
- Add URI parsing for better formatting and launching the swagger on the copied URL
=> Added URI parsing to values for transaction service URL

qrscanner/build.gradle, qrscanner/src/main/java/io/gnosis/safe/qrscanner/QRCodeScanActivity.kt, qrscanner/src/main/res/values/string.xml
Reference # 646 .
- Added retry logic if something that is not an Ethereum address is scanned
- Added alert dialog notifying the user of the error
=> QR Scan fix

app/src/main/java/io/gnosis/safe/ui/transaction/TransactionsViewModel.kt, app/src/test/java/io/gnosis/safe/ui/safe/settings/SafeSettingsViewModelTest.kt, data/src/main/java/io/gnosis/data/backend/dto/SafeInfoDto.kt, data/src/main/java/io/gnosis/data/backend/dto/TransactionDto.kt, data/src/main/java/io/gnosis/data/models/SafeInfo.kt, data/src/main/java/io/gnosis/data/models/Transaction.kt, data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt, data/src/main/java/io/gnosis/data/repositories/TransactionRepository.kt, data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt, data/src/test/java/io/gnosis/data/repositories/TransactionRepositoryTest.kt
Reference #665 .
- Passing `SafeInfo` to `getTransaction` method
- Calculation of status for each transaction, module and ethereum transactions are always assumed as `Success`
- Unit tests 
=> Transaction status

app/src/main/java/io/gnosis/safe/ui/safe/SafeOverviewBase.kt, app/src/main/java/io/gnosis/safe/ui/safe/assets/AssetsFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/settings/SettingsFragment.kt, app/src/main/java/io/gnosis/safe/ui/transaction/TransactionsFragment.kt, app/src/main/java/io/gnosis/safe/ui/transaction/TransactionsViewModel.kt, app/src/main/res/layout/fragment_transactions.xml, app/src/test/java/io/gnosis/safe/ui/transaction/TransactionsViewModelTest.kt
Reference #684 and #687 .
- Empty state is only shown if the loaded safe has no transactions
Remaining issues: the tool bar is not updated on safe change because it is not possible to inherit from `SafeOverviewBaseFragment` without losing tracking information. Not sure what to do about that.
=> Empty state to be shown only when a safe has no transactions

app/src/main/java/io/gnosis/safe/ui/safe/share/ShareSafeDialog.kt
Share dialog fragment is reused in navigation. When switching safes share dialog would have old safe details. Without resetting, those details will shortly appear before layout updates with active safe data.
=> Reset share dialog ui to prevent showing wrong safe's details

.buildkite/deployment.yml
This way any merge to master releases to `mainnet-release-internal` and `rinkeby-release-internal`. When we want to update external users we promote a build in https://console.firebase.google.com/project/safe-firebase-rinkeby/appdistribution/app/android:io.gnosis.safe.rinkeby/releases and https://console.firebase.google.com/project/safe-firebase-mainnet/appdistribution/app/android:io.gnosis.safe/releases respectively to the groups `mainnet-release` and `rinkeby-release`
=> Change the release group on firebase.

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt
Regarding #714  .
- Some bindings for queued txs were not setting the nonce
Before | After
------ | ------  
=> Nonce missing in queued transfers

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt, app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt, data/src/main/java/io/gnosis/data/models/Transaction.kt, data/src/main/java/io/gnosis/data/repositories/TransactionRepository.kt, data/src/test/java/io/gnosis/data/repositories/TransactionRepositoryTest.kt
Ticket #714 .
- Move calculation of incoming status to repository because we need access to data decoded to calculate it.
- Follow the rules laid out here: https://docs.google.com/document/d/1vhTu5NbB-6m8nE3cqTS3bRONigPO3NA5YkJqNTA6AOk/edit?skip_itp2_check=true **Except** the rules for custom tx because they are in a different issue/ticket and maybe obsoleted by the client service
- Tests added for new `incoming` calculation
- I sneaked in two fixes for missing confirmations text color and settings name (queued txs) 
- Also solves: https://github.com/gnosis/safe-android/issues/706 and  #712 
Before | After
------- | -----
=> Fix incoming status on confirmations/rejections

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionView.kt, app/src/main/res/layout/item_tx_change_mastercopy.xml, app/src/main/res/layout/item_tx_settings_change.xml, app/src/main/res/layout/item_tx_transfer.xml, app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt
Closes #763  .
This bug was not in the sprint. But for debugging the client gateway it would be really helpful to see nonces in historic transactions. 
- Show nonces, where available or nothing where not. 
=> Show nonces in historic transactions

app/src/main/java/io/gnosis/safe/ui/transactions/details/view/AmountView.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxTransferActionView.kt
Closes # .
- When an amount is incoming it is rendered in green in the details view
- 
- 
=> Incoming amounts should be green.

app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt
Closes #818 .
- Show sender on incoming tx and recipient on outgoing tx
=> Show sender on incoming tx and recipient on outgoing tx

app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsFragment.kt, app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsViewModel.kt, app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt, app/src/main/res/layout/fragment_coins.xml, app/src/main/res/layout/fragment_settings_safe.xml, app/src/main/res/layout/fragment_transaction_details.xml, app/src/main/res/layout/fragment_transaction_list.xml
Closes # .
- Add empty error state to coins list, tx list and safe settings
=> Show empty data error screen for safe settings

app/src/main/java/io/gnosis/safe/notifications/NotificationRepository.kt
semantic versioning validation for registering push notification devices on the transaction service was added => the versions android is sending have to be adjusted. iOS is sending x.y.z, so we will do the same.
- Adjust version sent to notification service when registering device
=> Send only x.y.z versions to notification service

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
Closes #830  .
- Page loading might return after switching to detail view and after `onDestroyView()` has been called and binding has been nulled Only access binding when this view is still at least STARTED
- Preventing submission in `loadTransactions()` unfortunately is not enough
- 
=> Prevent access to null binding after view is destroyed

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt, buildsystem/versions.gradle
Handles #623
Handles #809
Handles #828
Handles #835
Handles #855 
Handles #858
Handles #860
- Always load the latest state of the transactions
- Remove caching from tx list
- Fix retry handling for tx list
- Show retry error messages
- Fix tx list flashing issues
- Update list when navigating back from tx details
- Keep showing old data in case of an error on the pull to refresh
=> Always load transaction to display latest state; remove caching

app/src/main/java/io/gnosis/safe/di/modules/RepositoryModule.kt, data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt, data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
References #708 .
- Use `TransactionServiceApi` instead of blockchain validation for valid safe adding
=> Calling the right endpoint method for isValidSafe

data/src/main/java/io/gnosis/data/backend/dto/GateTransaction.kt, data/src/test/java/io/gnosis/data/adapters/DataMoshiTest.kt, data/src/test/resources/creation_with_null_implementation.json
Closes # .
- App should not throw an error on a creation tx without implementation or factory 
=> Error on null implementation

app/src/main/java/io/gnosis/safe/di/components/ViewComponent.kt, app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsFragment.kt, app/src/main/java/io/gnosis/safe/ui/assets/collectibles/CollectiblesViewHolderFactory.kt, app/src/main/java/io/gnosis/safe/ui/assets/collectibles/details/CollectiblesDetailsFragment.kt, app/src/main/res/layout/fragment_collectibles_details.xml, app/src/main/res/navigation/main_nav.xml, app/src/main/res/values/strings.xml
Handles #846 
- Add fragment for collectible details
- Navigate to collectible details screen from collectibles list
- Center-crop collectible list images
=> View collectible details

ci/prepare_env_buildkite.sh
Closes #874  .
- Add fetch before accessing tags with git
- Fetch shouldn't break anything and it makes the tag available
- 
=> Fetch tags before trying to read it

app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/view/Erc721View.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxTransferActionView.kt, app/src/main/res/layout/item_tx_transfer.xml, app/src/main/res/layout/view_tx_erc721.xml
Regading #792 .
- We don't show the token name only amount (and symbol) and tokenId below 
See: https://zpl.io/2GKm9xE and https://zpl.io/VDyzLp3
ENS | LBB in   | LBB out
---- | -------- | --------
=> Show amount (+/-1 <SYMBOL>) instead of name for NFTs

app/src/main/java/io/gnosis/safe/ui/StartActivity.kt, app/src/main/java/io/gnosis/safe/ui/safe/share/ShareSafeDialog.kt
Regarding #910 & #736  .
- Show correct Snackbar text when tapping address in dialog
- Open dialog when tapping address or name in app bar
- 
=> Share safe dialog

app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt, app/src/main/res/layout/fragment_transaction_details_creation.xml, app/src/main/res/layout/view_tx_status.xml
Regarding: #807 .
- Change Font for status to 16sp
- Don't show divider after advanced section if no etherscan link available
- The other issues in #807 have already been addressed
Awaiting Confirmation | Success | Cancelled | Failed 
-----------------------|---------|-----------|-------
=> Change font for status to 16sp by Using textDark style

app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsEditNameFragment.kt
Regarding #757 .
-  Prevent saving empty name and trim before saving
=> Prevent saving empty name and trim before saving

buildsystem/versions.gradle
Regarding #932 .
- Bumped several libs to the version recommended in https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android
=> Firebase Crashlytics: Bumping recommended libs to recommended versions

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt, app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt, data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt
Handles #719
hardcoded string extraction will happen in scope of https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/964
=> Add workaround for displaying fallback handler version

app/src/main/java/io/gnosis/safe/ui/settings/app/AppSettingsFragment.kt, app/src/main/res/layout/fragment_settings_app.xml, app/src/main/res/layout/item_import_owner_key.xml, app/src/main/res/layout/item_remove_owner_key.xml, app/src/main/res/values/strings.xml
Handles #946 
- Adds UI elements in `App Settings` fragment
- Provides callbacks with `snackbars` for now to which the actions should be attached once they are implemented
=> Adds UI elements for navigation/removal for owner key interactions

app/src/main/java/io/gnosis/safe/ui/splash/SplashActivity.kt, app/src/main/java/io/gnosis/safe/ui/splash/SplashViewModel.kt, app/src/main/java/io/gnosis/safe/ui/terms/TermsBottomSheetDialog.kt
Handles #970
- Prevents opening the Terms Sheet if it is already added
- Also does not re-open it (when it was dismissed) when coming back from background, because the last event is HideTerms in that case.
=> Prevent opening Terms Sheet if already added

app/src/main/java/io/gnosis/safe/ui/settings/app/AppSettingsFragment.kt
- Fix  snackbar showing import confirmation after key is removed from device
=> Reset owner import result after key removal

app/src/main/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/view/AddressItem.kt, app/src/main/java/io/gnosis/safe/ui/settings/view/NamedAddressItem.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsActionFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxSettingsActionView.kt, app/src/main/res/layout/fragment_collectibles_details.xml, app/src/main/res/layout/fragment_get_in_touch.xml, app/src/main/res/layout/fragment_settings_app.xml, app/src/main/res/layout/fragment_settings_app_advanced.xml, app/src/main/res/layout/fragment_settings_safe.xml, app/src/main/res/layout/fragment_transaction_details.xml, app/src/main/res/layout/fragment_transaction_details_advanced.xml, app/src/main/res/layout/fragment_transaction_details_creation.xml, app/src/main/res/layout/tx_details_custom.xml, app/src/main/res/layout/tx_details_settings_change.xml, app/src/main/res/layout/tx_details_transfer.xml, app/src/main/res/layout/view_address_item.xml, app/src/main/res/layout/view_mastercopy_item.xml, app/src/main/res/layout/view_multisend_action.xml, app/src/main/res/layout/view_named_address_item.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml
Handles #936 
**I think we need to make a decision on whether the last separator should be part of a custom view. And then make this consistent throughout the app.**
- Remove additional separator by extracting it from the mastercopy custom view
- Changing color of item separator in tx list (according to the zeplin layouts)
- Fixing height of several separators
- Fixing bottom margin for tx hash
- Fixing bottom margin for created date
- Fixing separator color and height for detail views
- Added ids to several separators to make layout debugging easier
- Added custom attribut to NamedAddressItem to disable/enable separator
**Notes for QA**: This might break the layout of tx list, tx details,  app settings, collectible details and safe settings. …
=> Creation layout

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt
Handles #1022
- Reload tx list only if scrolled past first tx item
=> Adjust reloading logic for tx list

app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt
=> Prevent previous error being shown for new address; keep entered invalid safe address visible for reference

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt
=> Set appropriate confirmations icon for queued custom transaction item

app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt
Handles #971 
Handles #972
After thorough investigation I was able to reproduce both crashes. The reason for both crashlytics issues is that fragment is not attached to context as callbacks are being invoked. This can happen if the input dialog is open and the user clicks on an incoming notification that navigates away from AddSafeFragment, not leaving the app. The input bottom sheet remains open though, thus any click on bottom sheet items results in a crash. 
Hiding input dialog solves the problem.
=> Hide input dialog if fragment is detached from context

app/src/main/java/io/gnosis/safe/Tracker.kt
Handles #1071 
- Add missing `screen_` prefix for all screen ids
=> Add missing screen_ prefix for all screen ids

data/build.gradle
Handles #1092
- https://safe-client-mainnet.staging.gnosisdev.com/ -> https://safe-client.mainnet.staging.gnosisdev.com/
- https://safe-client-rinkeby.staging.gnosisdev.com/ -> https://safe-client.rinkeby.staging.gnosisdev.com/
=> Update client gateway urls for staging

app/build.gradle, buildsystem/android_library.gradle, data/build.gradle
Handles #868
- adds flavor profile
- Activate leak canary for this flavor
**Remark: You need to add a "profile" client  config in google-services.json to build with this flavor**
=> Add flavour profile and activate leak canary for it

app/src/main/java/io/gnosis/safe/utils/DateUtils.kt
Handles #1158
- Always use language en and take country from devices locale
=> Using language "en" and devices country to format dates and times.

app/src/main/java/io/gnosis/safe/ui/StartActivity.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/fiat/FiatListAdapter.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionsFragment.kt, app/src/main/res/layout/item_tx_queued_transfer.xml, app/src/main/res/layout/item_tx_transfer.xml, app/src/main/res/navigation/main_nav.xml
Handles #1190
Changes
- Ellipsize long token names for amounts
- Use en layout for currency names
- Open history tx tab when navigation from push notifications about transfers
=> Set active tab to history when navigating from transfer push

app/src/main/res/layout/view_tx_erc721.xml
Handles #1204 
- Use ShapeableImageView with circle appearance overlay
Before | After
------ | ------
=> Make NFT icons circles

app/src/main/java/io/gnosis/safe/helpers/AddressInputHelper.kt
Handles #1225
- Check if fragment.context is null
- Log error via Timber if context is null
=> Prevent crash when Fragment lost context.

app/src/main/java/io/gnosis/safe/ui/settings/view/KnownAddressLogoView.kt
Handles #1165 
Before | After
-------| -----
=> Add background after logo was loaded

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionView.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/viewdata/TransactionDetailsViewData.kt, app/src/main/java/io/gnosis/safe/utils/TxUtils.kt, app/src/main/res/layout/item_tx_queued_rejection.xml, app/src/main/res/layout/item_tx_rejection.xml, app/src/main/res/values/strings.xml, app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt, app/src/test/java/io/gnosis/safe/ui/transactions/details/viewdata/TransactionDetailsViewDataTest.kt, app/src/test/java/io/gnosis/safe/utils/TxUtilsKtTest.kt, data/src/main/java/io/gnosis/data/models/transaction/TransactionInfo.kt, data/src/test/java/io/gnosis/data/adapters/DataMoshiTest.kt, data/src/test/java/io/gnosis/data/repositories/TransactionRepositoryTest.kt, data/src/test/resources/custom.json, data/src/test/resources/tx_details_custom.json
Handles #1267
- Add `isCancellation` to `TransactionInfo.Custom`
- Populate `isCancellation` to `TransactionView.CustomTransaction` and `TransactionView.CustomTransactionQueued`
- Adjust tests
=> Parse isCancellation flag 

app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt, app/src/main/java/io/gnosis/safe/notifications/NotificationManager.kt, app/src/main/java/io/gnosis/safe/notifications/NotificationRepository.kt, app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeNameViewModel.kt, app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerSelectionViewModel.kt, app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsEditNameViewModel.kt, app/src/main/java/io/gnosis/safe/ui/settings/safe/SafeSettingsViewModel.kt, app/src/main/res/values/strings.xml, app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeNameViewModelTest.kt, app/src/test/java/io/gnosis/safe/ui/settings/SafeSettingsViewModelTest.kt, app/src/test/java/io/gnosis/safe/ui/settings/safe/SafeSettingsEditNameViewModelTest.kt
- Add Notification Channel Group per added safe
- Update Group when local safe name is changed
- Delete Notification Channel Group when a safe is removed from the app
- On app startup: Create Notification Channel Group per existing safe (this can be removed in a future update)
Home -> Safe Multisig -> App Info -> Notifications: 
=> Notification channels

app/src/main/java/io/gnosis/safe/ui/transactions/details/AdvancedTransactionDetailsFragment.kt
Handles #1222
- Don't show nonceItem and nonceSeparator if nonce is blank
Before | After
-------|------
=> Don't show nonceItem and nonceSeparator if nonce is blank

app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxStatusView.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/viewdata/TransactionDetailsViewData.kt, app/src/test/java/io/gnosis/safe/ui/transactions/details/viewdata/TransactionDetailsViewDataTest.kt
Handles #1298 
- Ignore safeAppInfo for reciepient display
Old | New
--- | ----
=> Use toInfo in recipient address. Ignore safeAppInfo for recipient

app/src/main/java/io/gnosis/safe/ui/settings/app/SettingsHandler.kt, app/src/test/java/io/gnosis/safe/ui/settings/app/SettingsHandlerTest.kt, buildsystem/coverage_report.gradle
Handles #1333 
- Removed `sorted` to returned list from backend fiat codes
- Added ignore pattern for jacoco for those using versions of java > 1.9
=> Fiat codes are no longer sorted in the client side

app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangePasscodeFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/DisablePasscodeFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/EnterPasscodeFragment.kt
Handles #1349 
- Hide keyboard only when dialog is confirmed
-
-
=> Hide keyboard only on confirmation

app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeCreatePasscodeFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangePasscodeFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeRepeatPasscodeFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/CreatePasscodeFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/DisablePasscodeFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/EnterPasscodeFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/RepeatPasscodeFragment.kt, app/src/main/res/values/strings.xml
Handles #1340 + #1274
- Set keyboard type numeric programmatically
- Change text for new passcode
- Revert keyboard close in onStop()
=> Force keyboard type

app/src/main/java/io/gnosis/safe/ui/transactions/details/ButtonStateHelper.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt, app/src/test/java/io/gnosis/safe/ui/transactions/details/ButtonStateHelperTest.kt
Handles #1346 
- Uses rejectors now to determine whteher rejection is possible
- Hides confirmation button if tx has been confirmed by current owner
=> Confirm button should not be on confirmed tx

app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/EnterPasscodeFragment.kt
Handles #1388, #1350
- Fix navigation for passcode reset in confirmation
-
-
=> Go back to tx details when resetting passcode

app/src/main/java/io/gnosis/safe/di/modules/RepositoryModule.kt, buildsystem/versions.gradle, data/src/main/java/io/gnosis/data/repositories/DummyDomainResolution.kt, data/src/main/java/io/gnosis/data/repositories/UnstoppableDomainsRepository.kt, data/src/main/java/io/gnosis/data/utils/ExcludeClassFromJacocoGeneratedReport.kt
Handles #1398
- Capture exception in initializing unstoppable dependency
- This does not fix the bug itself but it prevents crashing
- Until the lib gets an update, we should probably remove the menu entry.
=> Don't crash in initializer

buildsystem/versions.gradle
Handles #
- New library version. Should not fail on prod instances
=> New library version. Should not fail on prod instances

app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/EnterPasscodeFragment.kt
Handles #1412 
- Fix title when asking for passcode for confirmation or rejection
=> Fix title when asking for passcode for confirmation

app/src/main/java/io/gnosis/safe/ui/StartActivity.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/SettingsHandler.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt, app/src/main/java/io/gnosis/safe/ui/updates/UpdatesFragment.kt, app/src/main/java/io/gnosis/safe/ui/updates/UpdatesViewModel.kt, app/src/main/java/io/gnosis/safe/utils/SemVer.kt
Handles #1421
- Fail silently
- Don't handle notifications for depracated versions
- Show update screen when opening from push notification
=> Improve stability & prevent crashes on invalid version strings & ranges

data/src/main/java/io/gnosis/data/security/HeimdallEncryptionManager.kt
Handles #1429
- When creating new keys the right Keystore needs to be used
=> Fix keystore name

app/src/main/java/io/gnosis/safe/ui/StartActivity.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/EnterPasscodeFragment.kt
Handles #1462, #1465
- Show passcode prompt only once when going to background multiple times
- When updating from previous app version do not enable request passcode on app start
=> Don't start login prompt twice.

app/src/main/java/io/gnosis/safe/ui/StartActivity.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/EnterPasscodeFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeSettingsFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeUtils.kt, app/src/main/res/layout/fragment_passcode.xml, app/src/main/res/values/strings.xml
Handles #1469, #1470
- Use singleTop to show passcode fragment only once after sending app to background multiple times
- Try to show keyboard with a bigger delay and show button to reopen keyboard if that fails
=> Use launch single top instead of tracking opening and closing.

app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsAdapter.kt, app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsViewData.kt, app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsViewModel.kt, app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeOwnerFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeSettingsFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerEnterNameFragment.kt, app/src/main/res/layout/fragment_add_safe_owner.xml, app/src/main/res/layout/fragment_owner_name_enter.xml, app/src/main/res/navigation/main_nav.xml, app/src/main/res/values/strings.xml, data/src/main/java/io/gnosis/data/repositories/CredentialsRepository.kt, data/src/test/java/io/gnosis/data/repositories/CredentialsRepositoryTest.kt
Handles #1480
Handles #1487
Handles #1488
Handles #1501
- Disable passcode only when all sub options are disabled
- Rename import to save when adding created owner; fix confirmation snackbar
-  Adjust add safe flow & optionally proceed to add owner flow instead of just owner import
TODO: rename banner tracking event?
=> Adjust add owner flow

app/src/main/java/io/gnosis/safe/ui/settings/owner/OwnerSeedPhraseViewModel.kt
Handles #1431 
- I could not reproduce the problem even after generating more than 10000 keys
- We now check that a key entered by the suer can be used to sign
=> More key validation

app/build.gradle, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/ChangeRepeatPasscodeFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt, app/src/test/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModelTest.kt
Handles Crash in Passcode change on non bio devices
- do not try to store passcode if device does not support biometrics or biometrics are disabled
-
-
=> Passcode change crash on non bio devices

app/src/main/java/io/gnosis/safe/ui/settings/owner/list/OwnerListViewModel.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
Handles #1497 
- Check if passcode is required for confirmation
=> Do not request passcode for confirmation if it's off in passcode settings

data/build.gradle
The unsafe flavor should use the unified backend.
=> Fix url for unsafe flavor

app/src/main/java/io/gnosis/safe/ui/settings/view/MasterCopyItem.kt, app/src/main/java/io/gnosis/safe/utils/StringUtils.kt, app/src/main/java/io/gnosis/safe/utils/TxUtils.kt, app/src/main/res/values/static_strings.xml, app/src/test/java/io/gnosis/safe/ui/settings/SafeSettingsViewModelTest.kt, app/src/test/java/io/gnosis/safe/ui/settings/safe/AdvancedSafeSettingsViewModelTest.kt, app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt, app/src/test/java/io/gnosis/safe/utils/TxUtilsKtTest.kt, contracts/build.gradle, data/src/main/java/io/gnosis/data/models/SafeInfo.kt, data/src/main/java/io/gnosis/data/repositories/SafeRepository.kt, data/src/test/java/io/gnosis/data/repositories/SafeRepositoryTest.kt
Handles #1492
- Show the contract version "1.3.0 up to date"
- 1.1.1 and 1.2.0 versions should still be shown as "up to date".
- All supported versions: from 1.0.0 to 1.3.0 inclusive
- Disallow adding safe outside this version range
- Remove hardcoded versions & version strings
=> Show contracts v1.3.0 as "up to date" in Safe Settings

app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/PasscodeViewModel.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/RepeatPasscodeFragment.kt
Handles #1511
- catch IllegalStateException
- disable biometrics
=> Prevent crash when no fingerprints enrolled although BIOMETRIC_SUCCESS was returned

app/src/main/java/io/gnosis/safe/ui/settings/app/passcode/EnterPasscodeFragment.kt, app/src/main/java/io/gnosis/safe/utils/AppUtils.kt
Handles #1475 
Handles #1522
- Dismiss forgot passcode dialog on pause
- Close tx details page after forgot passcode was used
=> Close tx details page after forgot passcode was used

app/src/main/java/io/gnosis/safe/di/modules/ApplicationModule.kt, app/src/main/java/io/gnosis/safe/notifications/NotificationRepository.kt, app/src/main/java/io/gnosis/safe/notifications/firebase/HeimdallFirebaseService.kt, app/src/main/java/io/gnosis/safe/ui/StartActivity.kt
Handles #1752
Handles #1754 
- Receive and handle push notifications from Intercom
- Opening the push message should open App and show Intercom chat screen in a popover 
- Only open Intercom window after passcode is unlocked
Intercom android sdk creates it's own notification channels:
Because Intercom android sdk has closed api there is no direct way to adjust naming/structure of those channels.
Same goes for the format of push notification itself
It is possible to adjust the icon in the top left part though. I would see it as low priority now and propose to adjust it if needed in a future pr.
Here is example of a notification for a single message
=> Receive and handle Itercom push notifications

app/src/main/java/io/gnosis/safe/Tracker.kt, app/src/main/java/io/gnosis/safe/di/components/ViewComponent.kt, app/src/main/java/io/gnosis/safe/di/modules/ViewModelFactoryModule.kt, app/src/main/java/io/gnosis/safe/di/modules/ViewModule.kt, app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsAdapter.kt, app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsViewData.kt, app/src/main/java/io/gnosis/safe/ui/assets/coins/CoinsViewModel.kt, app/src/main/java/io/gnosis/safe/ui/safe/add/AddSafeFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/add/SafeInputView.kt, app/src/main/java/io/gnosis/safe/ui/safe/send_funds/AssetSelectionViewModel.kt, app/src/main/java/io/gnosis/safe/ui/safe/send_funds/SendAssetFragment.kt, app/src/main/java/io/gnosis/safe/ui/safe/send_funds/SendAssetViewModel.kt, app/src/main/java/io/gnosis/safe/ui/safe/send_funds/view/AssetAmountInputView.kt, app/src/main/java/io/gnosis/safe/ui/settings/view/NamedAddressItem.kt, app/src/main/res/layout/fragment_edit_advanced_params.xml, app/src/main/res/layout/fragment_owner_name_edit.xml, app/src/main/res/layout/fragment_send_asset.xml, app/src/main/res/layout/fragment_settings_safe_edit_name.xml, app/src/main/res/layout/view_asset_amount_input.xml, app/src/main/res/navigation/main_nav.xml, app/src/main/res/values/strings.xml
Handles #1784
- Add send asset screen
- Pass selected asset data relevant for asset transfer
- Amount input field
- Tracking
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
=> [Send funds] Send asset screen

app/src/main/res/layout/fragment_add_safe.xml, app/src/main/res/layout/fragment_chain_selection.xml, app/src/main/res/layout/item_chain.xml
Handles #1820 
Figma | light | dark
----- | ----  | ----
=> Body1 versus Subtitle in select network & enter safe name screen

app/src/main/res/values/static_strings.xml
Handles #1903
merge after licenses page is available under the new link.
=> Update licenses link

app/src/main/java/io/gnosis/safe/Tracker.kt, app/src/main/java/io/gnosis/safe/di/components/ViewComponent.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/AppSettingsFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/ChainPrefixAppSettingsFragment.kt, app/src/main/java/io/gnosis/safe/ui/settings/app/SettingsHandler.kt, app/src/main/res/layout/fragment_settings_app.xml, app/src/main/res/layout/fragment_settings_app_chain_prefix.xml, app/src/main/res/navigation/main_nav.xml, app/src/main/res/values/strings.xml
Handles #1919
- Chain prefix app settings screen
- UI only
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Chain prefix: App settings item 

app/src/main/java/io/gnosis/safe/di/components/ViewComponent.kt, app/src/main/java/io/gnosis/safe/di/modules/ViewModelFactoryModule.kt, app/src/main/java/io/gnosis/safe/di/modules/ViewModule.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/AdvancedTransactionDetailsFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxAdvancedParamsFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxEditFee1559Fragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxEditFeeLegacyFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxEditFeeViewModel.kt, app/src/main/res/layout/fragment_tx_edit_advanced_params.xml, app/src/main/res/layout/fragment_tx_edit_fee.xml, app/src/main/res/layout/fragment_tx_edit_fee_legacy.xml, app/src/main/res/navigation/main_nav.xml, app/src/main/res/values/strings.xml, app/src/test/java/io/gnosis/safe/ui/transactions/execution/TxEditFeeViewModelTest.kt
Handles #1932
- Add fragments for editing transaction fee (EIP-1559 and legacy)
- Add nav graph definitions
=> Edit transaction fee screen for EIP-1559 and legacy transactions

data/build.gradle
Handles #1950
- Update cgw url to https://safe-client-nest.staging.5afe.dev/ for staging and dev builds
=> Use nest version for all staging environments

app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxEditFeeViewModel.kt, app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewViewModel.kt, app/src/main/res/values/strings.xml
Handles #1976
Handles #1977 
Handles #1978
- Show errors when key balance is not sufficient to execute transaction
- By default select key with the highest balance
=> Handle insufficient and loading balances errors

app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewViewModel.kt, app/src/main/res/values/strings.xml, app/src/test/java/io/gnosis/safe/ui/safe/add/AddSafeNameViewModelTest.kt, app/src/test/java/io/gnosis/safe/ui/transactions/details/ConfirmRejectionViewModelTest.kt, data/src/main/java/io/gnosis/data/backend/rpc/RpcClient.kt, data/src/main/java/io/gnosis/data/models/Chain.kt, data/src/main/java/io/gnosis/data/repositories/UnstoppableDomainsRepository.kt, data/src/test/java/io/gnosis/data/repositories/ChainInfoRepositoryTest.kt, data/src/test/java/io/gnosis/data/repositories/UnstoppableRepositoryTest.kt
Handles #1988
Changes in this pr
- Remove obsolete rinkeby mentions
- Update Gnosis Chain Gas Estimation by 30%
=> Update Gnosis Chain Gas Estimation by 30%

app/src/main/java/io/gnosis/safe/di/modules/DatabaseModule.kt, app/src/main/java/io/gnosis/safe/di/modules/RepositoryModule.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/viewdata/TransactionDetailsViewData.kt, app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewViewModel.kt, app/src/test/java/io/gnosis/safe/ui/transactions/TransactionListViewModelTest.kt, app/src/test/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModelTest.kt, app/src/test/java/io/gnosis/safe/ui/transactions/execution/TxReviewViewModelTest.kt, buildsystem/versions.gradle, data/schemas/io.gnosis.data.db.HeimdallDatabase/10.json, data/src/androidTest/java/io/gnosis/data/db/HeimdallDatabaseTest.kt, data/src/main/java/io/gnosis/data/db/HeimdallDatabase.kt, data/src/main/java/io/gnosis/data/db/daos/TransactionLocalDao.kt, data/src/main/java/io/gnosis/data/models/TransactionLocal.kt, data/src/main/java/io/gnosis/data/repositories/TransactionLocalRepository.kt
Handles #1987
- Persist tx data submitted to execution locally
- Get tx receipt and update tx status to pending if it was not yet indexed
=> Monitor transaction submitted for execution

app/src/main/java/io/gnosis/safe/ui/safe/send_funds/SendAssetReviewViewModel.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxConfirmationsView.kt, app/src/main/res/values/strings.xml, data/build.gradle, data/src/main/java/io/gnosis/data/models/transaction/TransactionDetails.kt
Handles #1994 
- Show pending step
- Use different id to retrieve uncached tx details 
=> Gh 1994 - Show pending step, show up to date values

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt, data/src/main/java/io/gnosis/data/backend/GatewayApi.kt
Handles #1995
- The txdetail calls do not have a timezone offset
=> GH-1995 - Removed offset as we do the timezone handling in the client. 

app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsViewModel.kt
Handles #
before | after 
-------|------
=> Allow execution of txs with more confirmations than necessary

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionView.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxType.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/viewdata/TransactionDetailsViewData.kt, app/src/main/java/io/gnosis/safe/utils/TxUtils.kt, app/src/main/res/layout/fragment_transaction_details.xml, app/src/main/res/layout/item_tx_queued_swap_order.xml, app/src/main/res/layout/item_tx_swap_order.xml, app/src/main/res/values/strings.xml, data/src/main/java/io/gnosis/data/adapters/MoshiBuilder.kt, data/src/main/java/io/gnosis/data/models/transaction/Transaction.kt, data/src/main/java/io/gnosis/data/models/transaction/TransactionInfo.kt
Handles #2025 
- Transaction type and related changes to display it.
=> Introducing a transaction type.

data/src/main/java/io/gnosis/data/utils/SafeTxHash.kt
Handles #2044
- Adds 'refundReceiver' to the safeTxHash calculation.
=> GH-2044 fixed missing field in the safeTxHash calculation.

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionView.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/view/TxType.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/viewdata/TransactionDetailsViewData.kt, app/src/main/java/io/gnosis/safe/utils/TxUtils.kt, app/src/main/res/values/strings.xml, data/src/main/java/io/gnosis/data/adapters/MoshiBuilder.kt, data/src/main/java/io/gnosis/data/models/transaction/Transaction.kt, data/src/main/java/io/gnosis/data/models/transaction/TransactionInfo.kt, data/src/main/java/io/gnosis/data/utils/SafeTxHash.kt
Handles #2046
- Added new transaction types
=> GH-2046 added two new transaction types

app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewHolderFactory.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListViewModel.kt, app/src/main/java/io/gnosis/safe/ui/transactions/TransactionView.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/TransactionDetailsFragment.kt, app/src/main/java/io/gnosis/safe/ui/transactions/details/viewdata/TransactionDetailsViewData.kt, app/src/main/java/io/gnosis/safe/ui/transactions/execution/TxReviewFragment.kt, data/src/main/java/io/gnosis/data/models/transaction/TransactionInfo.kt
Handles #2049
- Added new transaction display names
=> GH-2049 changed the display strings based on order types
